/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.ClasseProdutoBD;
import Conection.FornecedorBD;
import Conection.MarcaBD;
import Conection.ProdutoBD;
import Objetos.ClasseProduto;
import Objetos.Fornecedor;
import Objetos.Produto;
import ferramentas.ComboBoxClasse;
import ferramentas.ComboBoxFornecedor;
import ferramentas.ComboBoxMarca;
import ferramentas.TabelaProdutos;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author user
 */
public class FormCadProduto extends javax.swing.JFrame {
    TabelaProdutos model;
    int  btnIncluirStatus=0;
    ProdutoBD bd;
    int idProdutos;
    List<Produto> listaProduto;
    Produto produto;
    ComboBoxFornecedor comboModelFornecedor;
    ComboBoxMarca comboModelMarca;
    ComboBoxClasse comboModelClasse;
    /**
     * Creates new form FormCadProduto
     */
    
    public FormCadProduto() {
        initComponents();
       
        preencherTabela();
    }
    private void preencherTabela(){
        bd = new ProdutoBD();
         comboModelFornecedor= new ComboBoxFornecedor();
        ComboFornecedor.setModel(comboModelFornecedor);
        comboModelClasse = new ComboBoxClasse();
       ComboClasse.setModel(comboModelClasse);
        comboModelMarca = new ComboBoxMarca();
        ComboMarca.setModel(comboModelMarca);
        try {
            listaProduto=bd.getListaProduto();
            model = new TabelaProdutos(listaProduto);
            tabelaProduto.setModel(model);
            tabelaProduto.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            
        } catch (Exception ex) {
            Logger.getLogger(FormCadProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void excluir(){
        int linhaSelecionada = -1;
        Produto produto;
        linhaSelecionada = tabelaProduto.getSelectedRow();
        if (linhaSelecionada >= 0) { 
            int idProduto = (int) tabelaProduto.getValueAt(linhaSelecionada, 0);
          
            ProdutoBD dao = new ProdutoBD();
            dao.removerProduto(idProduto);
            preencherTabela();
            
    }                                          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGuia = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        panelCadastro = new javax.swing.JPanel();
        edtVenda = new javax.swing.JTextField();
        edtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtCusto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtQuantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtEstoqueMinimo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboMarca = new javax.swing.JComboBox();
        btnAdicionarMarca = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboClasse = new javax.swing.JComboBox();
        btnAdicionarClasse = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        ComboFornecedor = new javax.swing.JComboBox();
        btnAdicionarFornecedor = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        edtCodBarras = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        PanelGuia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGuiaMouseClicked(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaProduto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PanelGuia.addTab("Seleção", jPanel1);

        edtCodigo.setEditable(false);

        jLabel3.setText("Preço custo:");

        jLabel2.setText("Descrição:");

        jLabel4.setText("Preço Venda:");

        jLabel1.setText("Código:");

        jLabel5.setText("Quantidade:");

        jLabel6.setText("Estoque mínimo:");

        jLabel7.setText("Marca:");

        ComboMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdicionarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btnAdicionarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarMarcaActionPerformed(evt);
            }
        });

        jLabel8.setText("Classe:");

        ComboClasse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdicionarClasse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btnAdicionarClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarClasseActionPerformed(evt);
            }
        });

        jLabel9.setText("Fornecedor:");

        ComboFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAdicionarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btnAdicionarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarFornecedorActionPerformed(evt);
            }
        });

        jLabel10.setText("Código de barras:");

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(edtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(3, 3, 3)
                                .addComponent(edtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnAdicionarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCodBarras))
                            .addComponent(edtDescricao)))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(ComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(edtQuantidade))
                        .addGap(3, 3, 3)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(ComboClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionarClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(edtEstoqueMinimo))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelCadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdicionarClasse, btnAdicionarFornecedor, btnAdicionarMarca});

        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(btnAdicionarClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(edtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(edtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(edtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9)
                                .addComponent(ComboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdicionarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(edtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(edtEstoqueMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(ComboMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(48, 48, 48))
        );

        panelCadastroLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ComboClasse, ComboFornecedor, ComboMarca, btnAdicionarClasse, btnAdicionarFornecedor, btnAdicionarMarca});

        PanelGuia.addTab("Cadastro", panelCadastro);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirma.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.gif"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lixeira.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnGravar, btnIncluir});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGravar)
                        .addComponent(btnCancelar)
                        .addComponent(btnIncluir)
                        .addComponent(btnAlterar)
                        .addComponent(btnExcluir))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnGravar, btnIncluir});

        jMenu1.setText("Opções");

        jMenuItem1.setText("Importar de Xml");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGuia)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGuia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Produto produto = preencheProduto();
        ProdutoBD bd = new ProdutoBD();
        if(edtCodigo.getText().isEmpty()){
            try {
                bd.adicionarProduto(produto);
                PanelGuia.setEnabled(true);
                PanelGuia.setSelectedIndex(0);
                AbilidaOuDesabilitaBotoes();
                
                JOptionPane.showMessageDialog(this,"Produto Gravado com sucesso", "Sucesso",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(FormCadProduto.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Erro Ao Adicionar Produto " + ex);
            }
        }else{
            try {
                bd.AtualizaProduto(produto);
                PanelGuia.setEnabled(true);
                PanelGuia.setSelectedIndex(0);
                AbilidaOuDesabilitaBotoes();
                
                JOptionPane.showMessageDialog(this,"Produto Atualizado com sucesso", "Sucesso",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(FormCadProduto.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this,"Erro Ao Adicionar Produto " + ex);
            }
        }
        
        
        
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        limparcampos();
        btnIncluirStatus=1;
        btnIncluir.setEnabled(false);
btnAlterar.setEnabled(false);
btnExcluir.setEnabled(false);

        
        PanelGuia.setSelectedIndex(1);
        PanelGuia.setEnabled(false);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
limparcampos(); 
btnIncluirStatus=0;
btnIncluir.setEnabled(true);
btnAlterar.setEnabled(true);
btnExcluir.setEnabled(true);
PanelGuia.setEnabled(true);

                PanelGuia.setSelectedIndex(0);
               
                
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        
        int linhaSelecionada = -1;
        Produto produto = new Produto();
        linhaSelecionada = tabelaProduto.getSelectedRow();
        if (linhaSelecionada >= 0) { 
            
            idProdutos = (int) tabelaProduto.getValueAt(linhaSelecionada, 0);
            System.out.println(idProdutos);
            ProdutoBD dao = new ProdutoBD();
            System.out.println(idProdutos);
            
            produto= dao.getProdutoById(idProdutos);
            System.out.println(produto);
            this.produto=produto;
            btnIncluirStatus=1;
       
            PanelGuia.setSelectedIndex(1);
            edtCodigo.setText(String.valueOf(produto.getId()));
    edtCusto.setText(produto.getPreco_compra().toString());
    edtDescricao.setText(produto.getDescricao());
    edtEstoqueMinimo.setText(produto.getEstoque_minimo().toString());
    edtQuantidade.setText(produto.getQtd_estoque().toString());
    edtVenda.setText(produto.getPreco_venda().toString());
   
           
     ComboClasse.getModel().setSelectedItem(new ClasseProdutoBD().getClasseProdutoByDesc(produto.getClasse()));
            
    ComboFornecedor.getModel().setSelectedItem(new FornecedorBD().getFornecedorByNome(produto.getFornecedor()));
    ComboMarca.getModel().setSelectedItem(new MarcaBD().getMarcaByNome(produto.getMarca()));
    edtCodBarras.setText(String.valueOf(produto.getCodBarras()));
    
           
            
        } 
        else {
            JOptionPane.showMessageDialog(null, "É necesário selecionar uma linha.");
        }
         AbilidaOuDesabilitaBotoes();
         btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnIncluir.setEnabled(false);
            PanelGuia.setEnabled(false);
        
        
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAdicionarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarFornecedorActionPerformed
       FormCadFornecedor form = new FormCadFornecedor();
       form.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarFornecedorActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
preencherTabela();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnAdicionarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarMarcaActionPerformed
      FormCadMarcas form = new FormCadMarcas();
      form.setVisible(true);
    }//GEN-LAST:event_btnAdicionarMarcaActionPerformed

    private void btnAdicionarClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarClasseActionPerformed
        FormCadClasseProduto form = new FormCadClasseProduto();
        form.setVisible(true);
    }//GEN-LAST:event_btnAdicionarClasseActionPerformed

    private void PanelGuiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGuiaMouseClicked
        AbilidaOuDesabilitaBotoes();
                preencherTabela();
                if(PanelGuia.getSelectedIndex()==1){
                    PanelGuia.setEnabled(false);
                }
    }//GEN-LAST:event_PanelGuiaMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        excluir();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      FormProdutoNfe formProdutoNfe = new FormProdutoNfe();
      formProdutoNfe.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void AbilidaOuDesabilitaBotoes(){
        if(btnIncluirStatus==1){
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnIncluir.setEnabled(false);
        }
        if(PanelGuia.getSelectedIndex()==1){
            btnIncluirStatus=1;
           btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnIncluir.setEnabled(false); 
        }else{
            //btnIncluirStatus=0;
           btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnIncluir.setEnabled(true);  
        }
    }
    public void limparcampos(){
    edtCodigo.setText("");
    edtCusto.setText("");
    edtDescricao.setText("");
    edtEstoqueMinimo.setText("");
    edtQuantidade.setText("");
    edtVenda.setText("");
    ComboClasse.setSelectedIndex(-1);
    ComboFornecedor.setSelectedIndex(-1);
    ComboMarca.setSelectedIndex(-1);
    edtCodBarras.setText("");
}
    
    public Produto preencheProduto(){
    Produto produto = null;
    if(edtDescricao.getText().isEmpty()||edtCusto.getText().isEmpty()||edtVenda.getText().isEmpty()||edtQuantidade.getText().isEmpty()||edtEstoqueMinimo.getText().isEmpty()){
               JOptionPane.showMessageDialog(this,"Não é permitido campos nulos, verifique!");
           }else{
             produto = new Produto();
             if(edtCodigo.getText().isEmpty()){
                 
             }else{
             produto.setId(Integer.valueOf(edtCodigo.getText().toString()));
             }
    produto.setDescricao(edtDescricao.getText());
    produto.setPreco_compra(Double.valueOf(edtCusto.getText()));
    produto.setPreco_venda(Double.valueOf(edtVenda.getText()));
    produto.setClasse(ComboClasse.getSelectedItem().toString());
    produto.setFornecedor(ComboFornecedor.getSelectedItem().toString());
    produto.setQtd_estoque(Double.valueOf(edtQuantidade.getText()));
    produto.setMarca(ComboMarca.getSelectedItem().toString());
    produto.setEstoque_minimo(Double.valueOf(edtEstoqueMinimo.getText())); 
    if(edtCodBarras.getText().isEmpty()!=true){
         produto.setCodBarras(Long.valueOf(edtCodBarras.getText()));
    }
   
     return produto;
           }
       
    
    return produto;
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboClasse;
    private javax.swing.JComboBox ComboFornecedor;
    private javax.swing.JComboBox ComboMarca;
    private javax.swing.JTabbedPane PanelGuia;
    private javax.swing.JButton btnAdicionarClasse;
    private javax.swing.JButton btnAdicionarFornecedor;
    private javax.swing.JButton btnAdicionarMarca;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JTextField edtCodBarras;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtCusto;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtEstoqueMinimo;
    private javax.swing.JTextField edtQuantidade;
    private javax.swing.JTextField edtVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables

    

  public  void pegaProduto(Produto produto) {
      edtDescricao.setText(produto.getDescricao());
      edtCusto.setText(produto.getPreco_compra().toString());
      edtQuantidade.setText(produto.getQtd_estoque().toString());
      PanelGuia.setSelectedIndex(1);
      btnIncluirStatus=1;
      AbilidaOuDesabilitaBotoes();
      
    }
}
