/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.ConectionSingleton;
import Objetos.Cliente;
import Objetos.Funcionario;
import Objetos.Venda;
import Relatorios.ReportUtils;
import ferramentas.ComboBoxCliente;
import ferramentas.ComboBoxFuncionario;
import ferramentas.ComboBoxVenda;
import ferramentas.ProgressDialog;
import java.awt.Color;
import java.awt.Dimension;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author Marcos
 */
public class FormRelatorioVenda extends javax.swing.JFrame {

    /**
     * Creates new form FormRelatorioVenda
     */
    public FormRelatorioVenda() {
        initComponents();
        ComboParametro.setVisible(false);
        edtNun.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbCliente = new javax.swing.JRadioButton();
        rbVendedor = new javax.swing.JRadioButton();
        dataInicial = new com.toedter.calendar.JDateChooser();
        dataFinal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbNumeroVenda = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        rbOrdemCliente = new javax.swing.JRadioButton();
        rbOrdemVendedor = new javax.swing.JRadioButton();
        rbOrdemNumero = new javax.swing.JRadioButton();
        ComboParametro = new javax.swing.JComboBox();
        edtNun = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatorios Venda");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filtragem Relatorios de Venda.");
        jLabel1.setAutoscrolls(true);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        buttonGroup1.add(rbCliente);
        rbCliente.setText("Cliente");
        rbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbClienteItemStateChanged(evt);
            }
        });
        rbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbVendedor);
        rbVendedor.setText("Vendedor");
        rbVendedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbVendedorItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("De:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("a");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Filtrar Por:");

        buttonGroup1.add(rbNumeroVenda);
        rbNumeroVenda.setText("Número da Venda");
        rbNumeroVenda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbNumeroVendaItemStateChanged(evt);
            }
        });
        rbNumeroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNumeroVendaActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnFiltrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busca.png"))); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Ordenar Por:");

        buttonGroup2.add(rbOrdemCliente);
        rbOrdemCliente.setText("Cliente");
        rbOrdemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOrdemClienteActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbOrdemVendedor);
        rbOrdemVendedor.setText("Vendedor");

        buttonGroup2.add(rbOrdemNumero);
        rbOrdemNumero.setText("Número da Venda");
        rbOrdemNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOrdemNumeroActionPerformed(evt);
            }
        });

        ComboParametro.setEditable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbNumeroVenda))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbOrdemCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbOrdemNumero))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(rbOrdemVendedor))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(btnFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(147, 147, 147)
                                        .addComponent(jLabel5))
                                    .addComponent(edtNun, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 29, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbVendedor)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(ComboParametro, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addComponent(dataFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCliente)
                    .addComponent(rbVendedor)
                    .addComponent(rbNumeroVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboParametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(edtNun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOrdemCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbOrdemVendedor)
                    .addComponent(rbOrdemNumero))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFiltrar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbClienteActionPerformed

    private void rbNumeroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNumeroVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNumeroVendaActionPerformed
private void progressDialog(){
    
      
     
      Thread tread   = new Thread(new Runnable() {

          @Override
          public void run() {
              ProgressDialog p = new ProgressDialog();
          }
          
      });
       tread.start();
              
}
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbOrdemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOrdemClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOrdemClienteActionPerformed

    private void rbOrdemNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOrdemNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbOrdemNumeroActionPerformed

    private void rbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbClienteItemStateChanged
if(rbCliente.isSelected()){
    ComboBoxCliente model = new ComboBoxCliente();
    ComboParametro.setModel(model);
    ComboParametro.setVisible(true);
    edtNun.setVisible(false);
    validate();
   // AutoCompleteDecorator.decorate(ComboParametro);
}      
        
    }//GEN-LAST:event_rbClienteItemStateChanged

    private void rbVendedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbVendedorItemStateChanged
if(rbVendedor.isSelected()){
    ComboBoxFuncionario model = new ComboBoxFuncionario();
    ComboParametro.setModel(model);
    ComboParametro.setVisible(true);
    edtNun.setVisible(false);
    validate();
   // AutoCompleteDecorator.decorate(ComboParametro);
}        // TODO add your handling code here:
    }//GEN-LAST:event_rbVendedorItemStateChanged

    private void rbNumeroVendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbNumeroVendaItemStateChanged
if(rbNumeroVenda.isSelected()){
    edtNun.setVisible(true);
    ComboParametro.setVisible(false);
    validate();
}        // TODO add your handling code here:
    }//GEN-LAST:event_rbNumeroVendaItemStateChanged

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
     String ordem=null ;
        // progressDialog();
     if(rbOrdemCliente.isSelected()){
         ordem = "cliente";
     }else if(rbOrdemVendedor.isSelected()){
         ordem = "funcionario";
     }else if(rbOrdemNumero.isSelected()){
         ordem = "id";
     }
        
      if(rbCliente.isSelected()){
          Cliente cliente = (Cliente) ComboParametro.getSelectedItem();
          if(dataFinal.getDate()!=null&&dataFinal.getDate()!=null){
          relatorioCliente(ordem, cliente.getNome(),dataInicial.getDate(),dataFinal.getDate());
          } else{
              JOptionPane.showMessageDialog(this, "Selecione uma data inicial e uma final");
          }
      }else if(rbVendedor.isSelected()){
          Funcionario funcionario =(Funcionario) ComboParametro.getSelectedItem();
          if(dataFinal.getDate()!=null&&dataFinal.getDate()!=null){
          relatorioFuncionario(ordem, funcionario.getNome(),dataInicial.getDate(),dataFinal.getDate());
          } else{
              JOptionPane.showMessageDialog(this, "Selecione uma data inicial e uma final");
          }
      }else if(rbNumeroVenda.isSelected()){
          int id=Integer.valueOf(edtNun.getText());
          relatorioNVenda(ordem, id);
      }else{
          if(dataFinal.getDate()!=null&&dataFinal.getDate()!=null){
          relatorioVendaData(ordem,dataInicial.getDate(),dataFinal.getDate());
             
          }else{
                JOptionPane.showMessageDialog(this, "Selecione uma data inicial e uma final"); 
          }
      }
     
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private String converterData(Date date) {
     java.sql.Timestamp sq = new java.sql.Timestamp(date.getTime());
     SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
sdf.format(date); 
        System.out.println(sdf.format(date));
        return sdf.format(date);
        
    }
    private void relatorioCliente(String ordem, String filtro, Date dataini, Date datafim){
    
        InputStream inputStream = getClass().getResourceAsStream("/Relatorios/ReportVendaDatECliente.jasper");
     Map parametros = new HashMap();
        parametros.put("Cliente", filtro);
        parametros.put("DataIni", converterData(dataini));
         parametros.put("DataFim",converterData(datafim));
          parametros.put("ordem", ordem);
       
           
        try {
            ConectionSingleton conexaosingleton = ConectionSingleton.getInstancia();
         Connection connection = conexaosingleton.conectar();
 
            // abre o relatório
//            ReportUtils.openReport( "Relatorio de Vendas Por Data e Cliente", inputStream, parametros,
  //                  connection );
         FormProgressDialog pro = new FormProgressDialog( "Relatorio de Vendas Por Data e Cliente", inputStream, parametros,
    connection );
              pro.setVisible(true);
 
        } catch ( SQLException exc ) {
            exc.printStackTrace();
            //JOptionPane.showMessageDialog(this, "erro" +exc+edtObservacao.getText());
        } catch ( JRException exc ) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro" +exc);
        } catch (Exception ex) {
//            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "erro" +ex);
        }
    
}
    
    private void relatorioVendaData(String ordem, Date dataini, Date datafim){
    
    InputStream inputStream = getClass().getResourceAsStream("/Relatorios/ReportVendaData.jasper");
    Map parametros = new HashMap();
    
    parametros.put("DataIni", converterData(dataini));
    parametros.put("DataFim",converterData(datafim));
    parametros.put("ordem", ordem);
    
    
    try {
    ConectionSingleton conexaosingleton = ConectionSingleton.getInstancia();
    Connection connection = conexaosingleton.conectar();
    
    // abre o relatório
   // ReportUtils.openReport();
     FormProgressDialog pro = new FormProgressDialog( "Relatorio de Vendas Por Data", inputStream, parametros,
    connection );
              pro.setVisible(true);
    
    } catch ( SQLException exc ) {
    exc.printStackTrace();
    //JOptionPane.showMessageDialog(this, "erro" +exc+edtObservacao.getText());
    } catch ( JRException exc ) {
    exc.printStackTrace();
    JOptionPane.showMessageDialog(this, "erro" +exc);
    } catch (Exception ex) {
    //            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
    JOptionPane.showMessageDialog(this, "erro" +ex);
    }
    
    }
private void relatorioFuncionario(String ordem, String filtro, Date dataini, Date datafim){
     InputStream inputStream = getClass().getResourceAsStream("/Relatorios/ReportVendaDatEFuncionario.jasper");
     Map parametros = new HashMap();
        parametros.put("Funcionario",filtro);
        parametros.put("DataIni", converterData(dataini));
         parametros.put("DataFim",converterData(datafim));
          parametros.put("ordem", ordem);
       
           
        try {
            ConectionSingleton conexaosingleton = ConectionSingleton.getInstancia();
         Connection connection = conexaosingleton.conectar();
 
            // abre o relatório
//            ReportUtils.openReport( "Relatorio de Vendas Por Data e Funcionario", inputStream, parametros,
//                    connection );
         FormProgressDialog pro = new FormProgressDialog( "Relatorio de Vendas Por Data e Funcionario", inputStream, parametros,
    connection );
              pro.setVisible(true);
 
        } catch ( SQLException exc ) {
            exc.printStackTrace();
            //JOptionPane.showMessageDialog(this, "erro" +exc+edtObservacao.getText());
        } catch ( JRException exc ) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro" +exc);
        } catch (Exception ex) {
//            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "erro" +ex);
        }
    
    
}
private void relatorioNVenda(String ordem, int filtro){
    InputStream inputStream = getClass().getResourceAsStream("/Relatorios/ReportVendaById.jasper");
     Map parametros = new HashMap();
        parametros.put("id", filtro);
       parametros.put("ordem", ordem);
       
           
        try {
            ConectionSingleton conexaosingleton = ConectionSingleton.getInstancia();
         Connection connection = conexaosingleton.conectar();
 
            // abre o relatório
//            ReportUtils.openReport( "Relatorio de Vendas Por Código", inputStream, parametros,
                    //connection );
         FormProgressDialog pro = new FormProgressDialog( "Relatorio de Vendas Por Código", inputStream, parametros,
    connection );
              pro.setVisible(true);
 
        } catch ( SQLException exc ) {
            exc.printStackTrace();
            //JOptionPane.showMessageDialog(this, "erro" +exc+edtObservacao.getText());
        } catch ( JRException exc ) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro" +exc);
        } catch (Exception ex) {
//            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "erro" +ex);
        }
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRelatorioVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRelatorioVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboParametro;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dataFinal;
    private com.toedter.calendar.JDateChooser dataInicial;
    private javax.swing.JTextField edtNun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbNumeroVenda;
    private javax.swing.JRadioButton rbOrdemCliente;
    private javax.swing.JRadioButton rbOrdemNumero;
    private javax.swing.JRadioButton rbOrdemVendedor;
    private javax.swing.JRadioButton rbVendedor;
    // End of variables declaration//GEN-END:variables
}
