/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.CaixaBD;
import Conection.CaixaDiarioBD;
import Conection.ClienteBD;
import Conection.LancamentoCaixaBD;
import Conection.ParcelamentoBD;
import Conection.ServicosBD;
import Objetos.Caixa;
import Objetos.CaixaDiario;
import Objetos.Cliente;
import Objetos.LancamentoCaixa;
import Objetos.Parcelamento;
import Objetos.Servicos;
import ferramentas.TabelaParcelamento;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Marcos
 */
public class FormSelecionaParcelamento extends javax.swing.JFrame {
    TabelaParcelamento model;
    List<Parcelamento> lista = new ArrayList<Parcelamento>();
    ParcelamentoBD bd = new ParcelamentoBD();
    Parcelamento parcelamento=null;
    /**
     * Creates new form FormParcelamento
     */
    public FormSelecionaParcelamento() {
        initComponents();
        AbilitaDesabilitaCampos();
        
        model = new TabelaParcelamento(lista);
              TableParcelamento.setModel(model);
             
    }
    private void preencheTabela(List<Parcelamento> list){
        try {
            this.lista=list;
            if(lista.isEmpty()){
             JOptionPane.showMessageDialog(this, "Nenhum Registro Encontrado Com os Filtros Utilizados");
             model = new TabelaParcelamento(lista);
             TableParcelamento.setModel(model);
            }else{
                System.out.println(lista);
                model = new TabelaParcelamento(lista);
             TableParcelamento.setModel(model);
            }
        } catch (Exception ex) {
            Logger.getLogger(FormSelecionaParcelamento.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao listar Parcelamentos, Verifique os campos!!");
        }
       
    }
private void AbilitaDesabilitaCampos(){
    if(rbCliente.isSelected()){
        edtCliente.setVisible(true);
        labelCliente.setVisible(true);
        
        edtCodVenda.setVisible(false);
       
        edtSomenteData.setVisible(false);
        jDateDataInicial.setVisible(false);
        jDateDataFinal.setVisible(false);
        labelIntervalo.setVisible(false);
        
    }else if(rbCodVenda.isSelected()){
        labelCliente.setVisible(false);
        edtCliente.setVisible(false);
      
        edtCodVenda.setVisible(true);
        
        edtSomenteData.setVisible(false);
        jDateDataInicial.setVisible(false);
        jDateDataFinal.setVisible(false);
        labelIntervalo.setVisible(false);
    }else if(rbData.isSelected()){
        labelCliente.setVisible(false);
        edtCliente.setVisible(false);
       
        edtCodVenda.setVisible(false);
        
        edtSomenteData.setVisible(true);
        jDateDataInicial.setVisible(false);
        jDateDataFinal.setVisible(false);
        labelIntervalo.setVisible(false);
    }else if(rbIntervaloDatas.isSelected()){
        edtCliente.setVisible(false);
        labelCliente.setVisible(false);
       
        edtCodVenda.setVisible(false);
       
        edtSomenteData.setVisible(false);
        jDateDataInicial.setVisible(true);
        jDateDataFinal.setVisible(true);
        labelIntervalo.setVisible(true);
        
    }
    else if(rbVencidas.isSelected()){
        edtCliente.setVisible(false);
        labelCliente.setVisible(false);
     
        edtCodVenda.setVisible(false);
       
        edtSomenteData.setVisible(false);
        jDateDataInicial.setVisible(false);
        jDateDataFinal.setVisible(false);
        labelIntervalo.setVisible(false);
        
        
    }
    validate();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        FrameVizualizar = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        edtValor = new javax.swing.JTextField();
        edtCli = new javax.swing.JTextField();
        edtData = new javax.swing.JTextField();
        edtIdVenda = new javax.swing.JTextField();
        edtDocumento = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        edtStatus = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableParcelamento = new javax.swing.JTable();
        btnVizualizar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnDarBaixa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        edtSomenteData = new com.toedter.calendar.JDateChooser();
        rbData = new javax.swing.JRadioButton();
        rbCliente = new javax.swing.JRadioButton();
        edtCliente = new javax.swing.JTextField();
        edtCodVenda = new javax.swing.JTextField();
        rbCodVenda = new javax.swing.JRadioButton();
        chNotinha = new javax.swing.JCheckBox();
        jButton5 = new javax.swing.JButton();
        chSituacao = new javax.swing.JCheckBox();
        labelCliente = new javax.swing.JLabel();
        rbVencidas = new javax.swing.JRadioButton();
        rbIntervaloDatas = new javax.swing.JRadioButton();
        jDateDataInicial = new com.toedter.calendar.JDateChooser();
        labelIntervalo = new javax.swing.JLabel();
        jDateDataFinal = new com.toedter.calendar.JDateChooser();

        FrameVizualizar.setTitle("Vizualizar");
        FrameVizualizar.setResizable(false);
        FrameVizualizar.setSize(new java.awt.Dimension(600, 280));

        jLabel1.setText("Código:");

        jLabel2.setText("Cliente:");

        jLabel3.setText("Documento:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Venda Vinculada:");

        jLabel6.setText("Data:");

        edtId.setEditable(false);

        edtValor.setEditable(false);
        edtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtValorActionPerformed(evt);
            }
        });

        edtCli.setEditable(false);

        edtData.setEditable(false);

        edtIdVenda.setEditable(false);

        edtDocumento.setEditable(false);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        jButton6.setText("Dar Baixa");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jButton7.setText("Cancelar");

        jLabel7.setText("Status:");

        edtStatus.setEditable(false);
        edtStatus.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout FrameVizualizarLayout = new javax.swing.GroupLayout(FrameVizualizar.getContentPane());
        FrameVizualizar.getContentPane().setLayout(FrameVizualizarLayout);
        FrameVizualizarLayout.setHorizontalGroup(
            FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVizualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FrameVizualizarLayout.createSequentialGroup()
                        .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtCli, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FrameVizualizarLayout.createSequentialGroup()
                                .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)))
                        .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameVizualizarLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtValor))
                            .addGroup(FrameVizualizarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtDocumento))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameVizualizarLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(FrameVizualizarLayout.createSequentialGroup()
                        .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FrameVizualizarLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FrameVizualizarLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FrameVizualizarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {edtData, edtStatus});

        FrameVizualizarLayout.setVerticalGroup(
            FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameVizualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(edtIdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(edtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FrameVizualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parcelamentos");

        TableParcelamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableParcelamento.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(TableParcelamento);

        btnVizualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.gif"))); // NOI18N
        btnVizualizar.setText("Vizualizar");
        btnVizualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVizualizarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lixeira.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnDarBaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnDarBaixa.setText("Dar Baixa");
        btnDarBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarBaixaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Por:"));

        buttonGroup1.add(rbData);
        rbData.setText("Data de Vencimento");
        rbData.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbDataItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbCliente);
        rbCliente.setSelected(true);
        rbCliente.setText("CPF Cliente");
        rbCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbClienteItemStateChanged(evt);
            }
        });
        rbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbClienteActionPerformed(evt);
            }
        });

        edtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtClienteActionPerformed(evt);
            }
        });
        edtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtClienteKeyPressed(evt);
            }
        });

        buttonGroup1.add(rbCodVenda);
        rbCodVenda.setText("Codigo Da Venda");
        rbCodVenda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbCodVendaItemStateChanged(evt);
            }
        });

        chNotinha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chNotinha.setSelected(true);
        chNotinha.setText("Mostrar Somente Notinhas");
        chNotinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chNotinhaActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busca.png"))); // NOI18N
        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        chSituacao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        chSituacao.setSelected(true);
        chSituacao.setText("Mostrar Somente em Aberto");
        chSituacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSituacaoActionPerformed(evt);
            }
        });

        labelCliente.setText("Enter ou F8 para Buscar Cliente");

        buttonGroup1.add(rbVencidas);
        rbVencidas.setText("Todas Vencidas");
        rbVencidas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbVencidasItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbIntervaloDatas);
        rbIntervaloDatas.setText("Intervalo De Datas");
        rbIntervaloDatas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbIntervaloDatasItemStateChanged(evt);
            }
        });

        labelIntervalo.setText("a");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtSomenteData, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCodVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rbVencidas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbIntervaloDatas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelIntervalo)
                        .addGap(10, 10, 10)
                        .addComponent(jDateDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(chNotinha)
                            .addGap(119, 119, 119))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(chSituacao)
                            .addContainerGap()))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(labelCliente)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelCliente)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chNotinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chSituacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCliente)
                            .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbData)
                            .addComponent(edtSomenteData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCodVenda)
                            .addComponent(edtCodVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbVencidas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbIntervaloDatas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateDataInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateDataFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIntervalo, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVizualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDarBaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVizualizar)
                    .addComponent(btnExcluir)
                    .addComponent(btnDarBaixa))
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbClienteActionPerformed

    private void edtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtClienteActionPerformed

    private void rbClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbClienteItemStateChanged
AbilitaDesabilitaCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_rbClienteItemStateChanged

    private void rbDataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbDataItemStateChanged
AbilitaDesabilitaCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_rbDataItemStateChanged

    private void rbCodVendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbCodVendaItemStateChanged
AbilitaDesabilitaCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_rbCodVendaItemStateChanged

    private void chNotinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chNotinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chNotinhaActionPerformed

    private void edtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtValorActionPerformed

    private void btnVizualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVizualizarActionPerformed
 int linhaSelecionada = -1;
        Parcelamento parcelamento = null;
        linhaSelecionada = TableParcelamento.getSelectedRow();
        if (linhaSelecionada >= 0) { 
           int  id = (int) TableParcelamento.getValueAt(linhaSelecionada, 0);
          
            ParcelamentoBD dao = new ParcelamentoBD();
            parcelamento= dao.getItemById(id);
           System.out.println(parcelamento);
        edtCodVenda.setText(String.valueOf(parcelamento.getId_venda()));
        edtValor.setText(String.valueOf(parcelamento.getValor()));
        Cliente cliente = new ClienteBD().getClienteById(parcelamento.getId_cliente());
        edtCli.setText(cliente.getNome());
        edtId.setText(String.valueOf(parcelamento.getId()));
        edtData.setText(String.valueOf(parcelamento.getData()));
        edtDocumento.setText(parcelamento.getDocumento());
        edtStatus.setText(parcelamento.getStatus());
        edtIdVenda.setText(String.valueOf(parcelamento.getId_venda()));
        FrameVizualizar.setVisible(true);
        this.parcelamento=parcelamento;
        FrameVizualizar.setLocationRelativeTo(null);
        } else{
            JOptionPane.showMessageDialog(this, "Selecione uma linha");
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnVizualizarActionPerformed

    private void chSituacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chSituacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chSituacaoActionPerformed
private void SorterNotinha(){
    TabelaParcelamento tabela_model = (TabelaParcelamento) TableParcelamento.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
        TableParcelamento.setRowSorter(sorter);
        String text ="NOTINHA";
        if (text.length() == 0)
        {
             sorter.setRowFilter(null);
        }
        else
        {
             try
             {
                   sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text,5));
             }
             catch (PatternSyntaxException pse)
             {
                   System.err.println("Erro");
             }
        }
}
private void SorterSituação(){
    TabelaParcelamento tabela_model = (TabelaParcelamento) TableParcelamento.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
        TableParcelamento.setRowSorter(sorter);
        String text ="A RECEBER";
        if (text.length() == 0)
        {
             sorter.setRowFilter(null);
        }
        else
        {
             try
             {
                   sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text,6));
             }
             catch (PatternSyntaxException pse)
             {
                   System.err.println("Erro");
             }
        }
}
private void SorterLimpo(){
    TabelaParcelamento tabela_model = (TabelaParcelamento) TableParcelamento.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
        TableParcelamento.setRowSorter(sorter);
        String text ="A RECEBER";
        if (text.length() == 0)
        {
             sorter.setRowFilter(null);
        }
        else
        {
             try
             {
                   sorter.setRowFilter(RowFilter.regexFilter("(?i)",6));
             }
             catch (PatternSyntaxException pse)
             {
                   System.err.println("Erro");
             }
        }
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(rbCliente.isSelected()){
           Cliente cliente = new ClienteBD().getClienteByCpf(edtCliente.getText());
           preencheTabela(bd.getItemByIdCliente(cliente.getId()));
    }else if(rbCodVenda.isSelected()){
            try {
                preencheTabela(bd.getItemByVenda(Integer.valueOf(edtCodVenda.getText())));
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(this, "Insira Somente Numeros!!!");
            }
    }else if(rbData.isSelected()){
      
            preencheTabela(bd.getItemByData(edtSomenteData.getDate()));
    }else if(rbVencidas.isSelected()){
         preencheTabela(bd.getParcelamentosVencidos());
    }else if(rbIntervaloDatas.isSelected()){
         preencheTabela(bd.getParcelamentosByDatas(jDateDataInicial.getDate(), jDateDataFinal.getDate()));
    }
        
        if(chNotinha.isSelected()==true){
          SorterNotinha();
        }if(chSituacao.isSelected()==true){
            SorterSituação();
        }if(chNotinha.isSelected()==false && chSituacao.isSelected()==false){
            SorterLimpo();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
int linhaSelecionada = -1;
        Parcelamento parcelamento = null;
        linhaSelecionada = TableParcelamento.getSelectedRow();
        if (linhaSelecionada >= 0) { 
           int  id = (int) TableParcelamento.getValueAt(linhaSelecionada, 0);
          ParcelamentoBD dao = new ParcelamentoBD();
          int resposta =JOptionPane.showConfirmDialog(this, "Confirma Exclusão?", "Confirma?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if(resposta==JOptionPane.YES_OPTION){
            dao.removerItem(id);
             JOptionPane.showMessageDialog(this, "Exclusão realizada com sucesso, Refaça a Pesquisa.");
              List<Parcelamento> lista = new ArrayList<>();
             preencheTabela(lista);
          }
        } else{
            JOptionPane.showMessageDialog(this, "Selecione uma linha");
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed
public int verifica() {
        CaixaDiarioBD bd = new CaixaDiarioBD();
        CaixaBD caixabd = new CaixaBD();
        Caixa caixa = new Caixa();
        try {
            caixa = caixabd.getUltimoCaixaById(0);
            int ultimoidCaixa = caixa.getId();
            if (caixa.getStatus().equals("FECHADO")) {
                return 2;
            } else if (caixa.getStatus().equals("ABERTO")) {
                return 1;
            }
        } catch (Exception ex) {
            Logger.getLogger(FormCaixaDiario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro Ao Obter Dados " + ex);
        }
        return 0;

    }
    
    public void lancaEmCaixa(Double valor, String documento) {
        int resposta = verifica();
        if (resposta == 1) {
            LancamentoCaixa lancamento = new LancamentoCaixa();
            LancamentoCaixaBD bd = new LancamentoCaixaBD();
            CaixaDiario caixadiario = new CaixaDiario();
            CaixaDiarioBD diariobd = new CaixaDiarioBD();

            lancamento.setTipo(documento);

            caixadiario.setTipolancamento(documento);
            lancamento.setObs("Venda");

            caixadiario.setValor(valor);
            lancamento.setValor(valor);

            try {
                bd.adicionarlancamentoCaixa(lancamento);
                diariobd.adicionarClasseCaixa(caixadiario);
                //JOptionPane.showMessageDialog(this,"Lançamento adicionado com sucesso");
            } catch (Exception ex) {
                Logger.getLogger(FormFinalizaVenda.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Erro ao realizar lancamento " + ex);
            }

            //this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Caixa Fechado Abra-o");
        }

    }
    private void btnDarBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarBaixaActionPerformed
int linhaSelecionada = -1;
        Parcelamento parcelamento = null;
        linhaSelecionada = TableParcelamento.getSelectedRow();
        if (linhaSelecionada >= 0) { 
           int  id = (int) TableParcelamento.getValueAt(linhaSelecionada, 0);
          ParcelamentoBD dao = new ParcelamentoBD();
          int resposta =JOptionPane.showConfirmDialog(this, "Confirma Recebimento?", "Confirma?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if(resposta==JOptionPane.YES_OPTION){
             try {
                 
                   parcelamento = dao.getItemById(id);
                   if(parcelamento.getStatus().equals("RECEBIDO")){
                     JOptionPane.showMessageDialog(this, "A baixa ja foi realizada, não é possivel realizar a ação novamente");
                 }else{
                    parcelamento.setStatus("RECEBIDO");
                    lancaEmCaixa(parcelamento.getValor(), parcelamento.getDocumento());
                   dao.AtualizaItem(parcelamento);
                   JOptionPane.showMessageDialog(this, "Recebimento Registrado com sucesso!");
                   }
               } catch (Exception ex) {
                   Logger.getLogger(FormSelecionaParcelamento.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(this, "Erro ao Alterar Situação " + ex);
               }
          }
        }  else{
            JOptionPane.showMessageDialog(this, "Selecione uma linha!");
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnDarBaixaActionPerformed
void retornaCliente(Cliente cliente) {
      
       edtCliente.setText(cliente.getCpf());
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
DarBaixa();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void edtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER || evt.getKeyCode()==KeyEvent.VK_F8){
            FormSelecionaCliente form = new FormSelecionaCliente(this);
            form.setVisible(true);
        }
    }//GEN-LAST:event_edtClienteKeyPressed

    private void rbIntervaloDatasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbIntervaloDatasItemStateChanged
      AbilitaDesabilitaCampos();
    }//GEN-LAST:event_rbIntervaloDatasItemStateChanged

    private void rbVencidasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbVencidasItemStateChanged
AbilitaDesabilitaCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_rbVencidasItemStateChanged
private void DarBaixa(){
     if(parcelamento.getStatus().equals("RECEBIDO")){
                     JOptionPane.showMessageDialog(this, "A baixa ja foi realizada, não é possivel realizar a ação novamente");
                 }else{
    int resposta =JOptionPane.showConfirmDialog(this, "Confirma Recebimento?", "Confirma?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          if(resposta==JOptionPane.YES_OPTION){
             try {
                 
                  parcelamento.setStatus("RECEBIDO");
                    lancaEmCaixa(parcelamento.getValor(), parcelamento.getDocumento());
                   bd.AtualizaItem(parcelamento);
                   JOptionPane.showMessageDialog(this, "Recebimento Registrado com sucesso!");
                 
               } catch (Exception ex) {
                   Logger.getLogger(FormSelecionaParcelamento.class.getName()).log(Level.SEVERE, null, ex);
                   JOptionPane.showMessageDialog(this, "Erro ao Alterar Situação " + ex);
               }
             
             
          }
        }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaParcelamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSelecionaParcelamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame FrameVizualizar;
    private javax.swing.JTable TableParcelamento;
    private javax.swing.JButton btnDarBaixa;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVizualizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chNotinha;
    private javax.swing.JCheckBox chSituacao;
    private javax.swing.JTextField edtCli;
    private javax.swing.JTextField edtCliente;
    private javax.swing.JTextField edtCodVenda;
    private javax.swing.JTextField edtData;
    private javax.swing.JTextField edtDocumento;
    private javax.swing.JTextField edtId;
    private javax.swing.JTextField edtIdVenda;
    private com.toedter.calendar.JDateChooser edtSomenteData;
    private javax.swing.JTextField edtStatus;
    private javax.swing.JTextField edtValor;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateDataFinal;
    private com.toedter.calendar.JDateChooser jDateDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelIntervalo;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbCodVenda;
    private javax.swing.JRadioButton rbData;
    private javax.swing.JRadioButton rbIntervaloDatas;
    private javax.swing.JRadioButton rbVencidas;
    // End of variables declaration//GEN-END:variables
}
