/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;


import Conection.CaixaBD;
import Conection.CaixaDiarioBD;
import Conection.LancamentoCaixaBD;
import Objetos.Caixa;
import Objetos.CaixaDiario;
import Objetos.ClasseCaixa;
import Objetos.LancamentoCaixa;
import ferramentas.ComboBoxTipoLancamentoCaixa;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FormLancamentoCaixa extends javax.swing.JFrame {
    ComboBoxTipoLancamentoCaixa model ;
    FormCaixaDiario form;
    /**
     * Creates new form FormLancamentoCaixa
     */
    public FormLancamentoCaixa(FormCaixaDiario form) {
        initComponents();
        listar();
        this.form=form;
      int resultado = verifica();
        
      if(resultado!=1){
            JOptionPane.showMessageDialog(this, "Caixa Fechado, abra-o primeiro!");
           fechar();
        }
    }
    
    public void listar(){
        model = new ComboBoxTipoLancamentoCaixa();
        jComboBoxClasseLancamento.setModel(model);
    }
    
public void fechar(){
    this.dispose();
}
    private FormLancamentoCaixa() {
        
    }
    public int verifica(){
     CaixaDiarioBD   bd = new CaixaDiarioBD();
     CaixaBD caixabd= new CaixaBD();
     Caixa caixa = new Caixa();
        try {
         caixa=caixabd.getUltimoCaixaById(0);
           int ultimoidCaixa=caixa.getId();
        if(caixa.getStatus().equals("FECHADO")){
           return 2;
        }else if(caixa.getStatus().equals("ABERTO")){
        return 1;
        }
        } catch (Exception ex) {
            Logger.getLogger(FormCaixaDiario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Erro Ao Obter Dados " +ex);
        }
        return 0;
         
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxClasseLancamento = new javax.swing.JComboBox();
        edtValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        edtDetalhe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lançamento em caixa");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jComboBoxClasseLancamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        edtValor.setToolTipText("Valor do lançamento ");

        jLabel1.setText("Valor:");

        edtDetalhe.setToolTipText("Detalhe do lançamento a ser gravado.");

        jLabel2.setText("Detalhe:");

        jLabel3.setText("Tipo:");

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBoxClasseLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(edtDetalhe))
                                .addGap(20, 20, 20))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxClasseLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtDetalhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(14, 14, 14))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {edtDetalhe, jComboBoxClasseLancamento});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       int resposta=JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar?","Cancelar", JOptionPane.YES_NO_OPTION);
       if(resposta==JOptionPane.YES_OPTION){
           this.dispose();
       }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
      int resposta=verifica();
      if(resposta==1){
        LancamentoCaixa lancamento = new  LancamentoCaixa();
        LancamentoCaixaBD bd = new LancamentoCaixaBD();
        CaixaDiario caixadiario = new CaixaDiario();
        CaixaDiarioBD diariobd = new CaixaDiarioBD();
      if((edtDetalhe.getText().isEmpty()) || (edtValor.getText().isEmpty()) || (jComboBoxClasseLancamento.getSelectedItem()==null) ){
            JOptionPane.showMessageDialog(this,"Confirme os campos, não é permitido nulos");
       }else{
            ClasseCaixa classe = (ClasseCaixa) jComboBoxClasseLancamento.getSelectedItem();
            
            
            
            lancamento.setTipo(classe.getDescricao());
            
            caixadiario.setTipolancamento(classe.getDescricao());
             lancamento.setObs(edtDetalhe.getText());
              String txt =edtValor.getText();
             if(classe.getOperador().equals("Soma")){
                 caixadiario.setValor(Double.valueOf(""+edtValor.getText()));
             lancamento.setValor(Double.valueOf(edtValor.getText()));
             }else{
                 caixadiario.setValor(Double.valueOf("-"+edtValor.getText()));
             lancamento.setValor(Double.valueOf(edtValor.getText()));
             }
            
             
             
             
           int opcao= JOptionPane.showConfirmDialog(this,"Confirma lançamento?","Confirmação",JOptionPane.YES_NO_OPTION);
                    if(opcao==JOptionPane.YES_OPTION){
                            try {
                                bd.adicionarlancamentoCaixa(lancamento);
                                diariobd.adicionarClasseCaixa(caixadiario);
                                JOptionPane.showMessageDialog(this,"Lançamento adicionado com sucesso");
                                form.retornaLancamento(lancamento);
        this.dispose();
                            } catch (Exception ex) {
                                Logger.getLogger(FormLancamentoCaixa.class.getName()).log(Level.SEVERE, null, ex);
                            JOptionPane.showMessageDialog(this,"Erro ao gravar lançamento");
                            }
                    }
        }
      }else{
          JOptionPane.showMessageDialog(this,"Caixa Fechado Abra-o");
      }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       FormCadTipoLancamento form = new FormCadTipoLancamento();
       form.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
listar();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLancamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLancamentoCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtDetalhe;
    private javax.swing.JTextField edtValor;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBoxClasseLancamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
