/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.OrdemServicoBD;
import Objetos.OrdemServico;
import ferramentas.TabelaOrdemServico;
import java.text.DateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class FormSelecionaOS extends javax.swing.JFrame {
FormOrdemServico frame;
    TabelaOrdemServico model ;
    List<OrdemServico> listaOs;
    private int idOs;
    OrdemServicoBD bd = new OrdemServicoBD();
    /**
     * Creates new form FormSelecionaCliente
     */
    public FormSelecionaOS() {
        initComponents();
        preencheTabela();
         edtPesquisa.setVisible(false);
        SelecionaData.setVisible(false);
        btnPesquisar.setVisible(false);
         this.getRootPane().setDefaultButton(btnSeleciona);
    }
     public FormSelecionaOS(FormOrdemServico form) {
        initComponents();
        this.frame=form;
        edtPesquisa.setVisible(false);
        SelecionaData.setVisible(false);
          btnPesquisar.setVisible(false);
       this.getRootPane().setDefaultButton(btnSeleciona);
    preencheTabela();
        
       
    }
     private void preencheTabela(){
         try {
             listaOs=bd.getListaOrdemServico();
             model = new TabelaOrdemServico(listaOs);
             tableOs.setModel(model);
       
    } catch (Exception ex) {
        Logger.getLogger(FormSelecionaOS.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Erro ao listar ordens de serviço "+ex);
    }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOs = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnSeleciona = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbCliente = new javax.swing.JRadioButton();
        rbNOs = new javax.swing.JRadioButton();
        rbFuncionario = new javax.swing.JRadioButton();
        rbData = new javax.swing.JRadioButton();
        edtPesquisa = new javax.swing.JTextField();
        SelecionaData = new com.toedter.calendar.JDateChooser();
        btnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Cliente");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        tableOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableOs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableOsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableOs);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnSeleciona.setText("Selecionar");
        btnSeleciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar por:"));

        buttonGroup1.add(rbCliente);
        rbCliente.setText("Cliente");
        rbCliente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbClienteStateChanged(evt);
            }
        });

        buttonGroup1.add(rbNOs);
        rbNOs.setText("Nº OS");
        rbNOs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbNOsStateChanged(evt);
            }
        });

        buttonGroup1.add(rbFuncionario);
        rbFuncionario.setText("Funcionario");
        rbFuncionario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbFuncionarioStateChanged(evt);
            }
        });

        buttonGroup1.add(rbData);
        rbData.setText("Data Entrada");
        rbData.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDataStateChanged(evt);
            }
        });

        edtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtPesquisaKeyPressed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busca.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbNOs)
                        .addGap(18, 18, 18)
                        .addComponent(rbFuncionario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbCliente)
                        .addGap(12, 12, 12)
                        .addComponent(rbData)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(SelecionaData, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbNOs)
                            .addComponent(rbFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCliente)
                            .addComponent(rbData)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelecionaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSeleciona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleciona)
                    .addComponent(btnIncluir)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionaActionPerformed
        // TODO add your handling code here:
        seleciona();
    }//GEN-LAST:event_btnSelecionaActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
      frame.requestFocusInWindow();
      frame.limparCampos();
      frame.desbloquearCampos();
      this.dispose();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       preencheTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tableOsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableOsMouseClicked
        if (evt.getClickCount() > 1) {  
 seleciona();
}  
        
    }//GEN-LAST:event_tableOsMouseClicked

    private void edtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPesquisaKeyPressed
TabelaOrdemServico tabela_model = (TabelaOrdemServico) tableOs.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
        tableOs.setRowSorter(sorter);
        String text ="(?i)"+edtPesquisa.getText().toUpperCase();
        if (text.length() == 0)
        {
             sorter.setRowFilter(null);
        }
        else
        {
             try
             {
                 if(rbCliente.isSelected()){
                   sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text, 1));
                 }else if(rbFuncionario.isSelected()){
                 sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text,5));

                 }else if(rbNOs.isSelected()){
                sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text,0));

                 }
             }
             catch (PatternSyntaxException pse)
             {
                   System.err.println("Erro");
             }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_edtPesquisaKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void rbNOsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbNOsStateChanged
        // TODO add your handling code here:
        if(rbNOs.isSelected()){
        if(edtPesquisa.isVisible()==true){
              btnPesquisar.setVisible(false);
            SelecionaData.setVisible(false);
        }else{
            edtPesquisa.setVisible(true);
            SelecionaData.setVisible(false);
              btnPesquisar.setVisible(false);
        }
        }
        validate();
       
    }//GEN-LAST:event_rbNOsStateChanged

    private void rbFuncionarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbFuncionarioStateChanged
if(rbFuncionario.isSelected()){
        if(edtPesquisa.isVisible()==true){
            SelecionaData.setVisible(false);
              btnPesquisar.setVisible(false);
        }else{
            edtPesquisa.setVisible(true);
            SelecionaData.setVisible(false);
              btnPesquisar.setVisible(false);
        }
        }
        validate();        // TODO add your handling code here:
    }//GEN-LAST:event_rbFuncionarioStateChanged

    private void rbClienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbClienteStateChanged
if(rbCliente.isSelected()){
        if(edtPesquisa.isVisible()==true){
            SelecionaData.setVisible(false);
              btnPesquisar.setVisible(false);
        }else{
            edtPesquisa.setVisible(true);
              btnPesquisar.setVisible(false);
            SelecionaData.setVisible(false);
        }
        }
        validate();        // TODO add your handling code here:
    }//GEN-LAST:event_rbClienteStateChanged

    private void rbDataStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDataStateChanged
if(rbData.isSelected()){
        if(edtPesquisa.isVisible()==true){
            SelecionaData.setVisible(true);
              btnPesquisar.setVisible(true);
            edtPesquisa.setVisible(false);
        }else{
            edtPesquisa.setVisible(false);
              btnPesquisar.setVisible(true);
            SelecionaData.setVisible(true);
        }
        }
        validate();        // TODO add your handling code here:
    }//GEN-LAST:event_rbDataStateChanged

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       TabelaOrdemServico tabela_model = (TabelaOrdemServico) tableOs.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
        tableOs.setRowSorter(sorter);
        
        DateFormat f = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String text ="(?i)"+f.format(SelecionaData.getDate());
        if (text.length() == 0)
        {
             sorter.setRowFilter(null);
        }
        else
        {
             try
             {
                 
                   sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text, 6));
                 
             }
             catch (PatternSyntaxException pse)
             {
                   System.err.println("Erro");
             }
        } 
        
        
        
        
        
        System.out.println();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed
    public void seleciona() {
        int linhaSelecionada = -1;
        OrdemServico ordem = null;
        linhaSelecionada = tableOs.getSelectedRow();
        if (linhaSelecionada >= 0) {
            idOs = (int) tableOs.getValueAt(linhaSelecionada, 0);

            ordem = bd.getOrdemSById(idOs);
            System.out.println(ordem);
            if (frame == null) {
                frame = new FormOrdemServico();
                frame.retornaOrdemServico(ordem);
                frame.setVisible(true);
            } else {
                frame.retornaOrdemServico(ordem);
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um Cliente");
        }

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSelecionaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSelecionaOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser SelecionaData;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSeleciona;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbData;
    private javax.swing.JRadioButton rbFuncionario;
    private javax.swing.JRadioButton rbNOs;
    private javax.swing.JTable tableOs;
    // End of variables declaration//GEN-END:variables
}
