/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.ConectionSingleton;
import Conection.ContasPagarBD;
import Objetos.ContasPagar;
import Relatorios.ReportUtilsDireto;
import ferramentas.TabelaContasPagar;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author USUARIO
 */
public class FormContasPagar extends javax.swing.JFrame {
List<ContasPagar> lista;
    /**
     * Creates new form FormContasPagar
     */
    public FormContasPagar() {
        initComponents();
        preencheTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGuia = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaContas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        edtPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        edtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edtValor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboSituacao = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contas a Pagar");
        setResizable(false);

        tabelaContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaContas);

        jLabel6.setText("Pesquisa:");

        edtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtPesquisaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelGuia.addTab("Seleção", jPanel1);

        jLabel2.setText("Descrição:");

        jLabel1.setText("Código:");

        edtCodigo.setEditable(false);

        jLabel3.setText("Valor:");

        edtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtValorActionPerformed(evt);
            }
        });

        jLabel4.setText("Situação:");

        comboSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Aberto", "Paga" }));
        comboSituacao.setSelectedIndex(-1);

        jLabel5.setText("Data Vencimento:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(comboSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        PanelGuia.addTab("Cadastro", jPanel2);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirma.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.gif"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lixeira.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnGravar, btnIncluir});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGravar)
                        .addComponent(btnCancelar)
                        .addComponent(btnIncluir)
                        .addComponent(btnAlterar)
                        .addComponent(btnExcluir))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnExcluir, btnGravar, btnIncluir});

        jMenu1.setText("Opções");

        jMenuItem2.setText("Dar Baixa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Imprimir Recibo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Relatorios");

        jMenuItem3.setText("Relatorio de Contas em Aberto Por Data");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGuia)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (edtDescricao.getText().isEmpty()==false && edtValor.getText().isEmpty()==false) {
            ContasPagar marca = preencheContas();
            ContasPagarBD bd = new ContasPagarBD();
            if (edtCodigo.getText().isEmpty()) {
                try {
                    bd.adicionarContasPagar(marca);
                    JOptionPane.showMessageDialog(this, "Sucesso ao adicionar " + marca.getDescricao().toString() + "");
                } catch (Exception ex) {
                    Logger.getLogger(FormContasPagar.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                try {
                    marca.setId(Integer.valueOf(edtCodigo.getText()));
                    bd.AtualizaConta(marca);
                    JOptionPane.showMessageDialog(this, "Sucesso ao atualizar " + marca.getDescricao().toString() + "");
                } catch (Exception ex) {
                    Logger.getLogger(FormContasPagar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            PanelGuia.setSelectedIndex(0);
            btnIncluir.setEnabled(true);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            PanelGuia.setEnabled(true);
            preencheTabela();
            edtCodigo.setText("");
            edtDescricao.setText("");
            edtValor.setText("");
            comboSituacao.setSelectedIndex(-1);
            jDate.setDate(null);
        }else{
            JOptionPane.showMessageDialog(this, "Não é permitido campos nulos.");
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        PanelGuia.setSelectedIndex(1);
        btnIncluir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        PanelGuia.setEnabled(false);
    }//GEN-LAST:event_btnIncluirActionPerformed
private void excluir(){
     int linhaSelecionada = -1;
    int id;
        ContasPagar conta = new ContasPagar();
        linhaSelecionada = tabelaContas.getSelectedRow();
        if (linhaSelecionada >= 0) { 
            id = (int) tabelaContas.getValueAt(linhaSelecionada, 0);
           
            ContasPagarBD bd = new ContasPagarBD();
            
            int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja apagar o registro?\n A operação não pode ser desfeita.", "Confirma Exclusão?", JOptionPane.YES_NO_OPTION);
            if (resposta==JOptionPane.YES_OPTION) {
                bd.removerContasPagar(id);
                JOptionPane.showMessageDialog(this, "Operação realizada com sucesso.");
                preencheTabela();
            }
}
}
    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
     alterar();
    }//GEN-LAST:event_btnAlterarActionPerformed
private void alterar(){
    int linhaSelecionada = -1;
    int id;
        ContasPagar conta = new ContasPagar();
        linhaSelecionada = tabelaContas.getSelectedRow();
        if (linhaSelecionada >= 0) { 
            id = (int) tabelaContas.getValueAt(linhaSelecionada, 0);
           
            ContasPagarBD bd = new ContasPagarBD();
            
            
            conta= bd.getContasPagarById(id);
            System.out.println(conta);
           edtCodigo.setText(String.valueOf(conta.getId()));
           edtDescricao.setText(conta.getDescricao());
           edtValor.setText(String.valueOf(conta.getValor()));
           comboSituacao.setSelectedIndex(conta.getSituacao());
           jDate.setDate(conta.getData());
           
            PanelGuia.setSelectedIndex(1);
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnIncluir.setEnabled(false);
        } 
        else {
            JOptionPane.showMessageDialog(null, "É necesário selecionar uma linha.");
        }

}
private void baixar(){
    int linhaSelecionada = -1;
    int id;
        ContasPagar conta = new ContasPagar();
        linhaSelecionada = tabelaContas.getSelectedRow();
        if (linhaSelecionada >= 0) { 
            id = (int) tabelaContas.getValueAt(linhaSelecionada, 0);
           
            ContasPagarBD bd = new ContasPagarBD();
            
            
            conta= bd.getContasPagarById(id);
            System.out.println(conta);
            if (conta.getSituacao()==0) {
                int resposta = JOptionPane.showConfirmDialog(this, "Confirma Baixa?", "Confirma Baixa?", JOptionPane.YES_NO_OPTION);
                if (resposta==JOptionPane.YES_OPTION) {
                    conta.setSituacao(1);
                    try {
                        bd.AtualizaConta(conta);
                        JOptionPane.showMessageDialog(this, "Sucesso ao Dar Baixa");
                        preencheTabela();
                    } catch (Exception ex) {
                        Logger.getLogger(FormContasPagar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(this, "A Conta Selecionada ja encontra-se baixada.");
            }
        } 
        else {
            JOptionPane.showMessageDialog(null, "É necesário selecionar uma linha.");
        }

}
    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
   excluir();

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void edtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPesquisaKeyPressed
TabelaContasPagar tabela_model = (TabelaContasPagar) tabelaContas.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
       tabelaContas.setRowSorter(sorter);
        String text = edtPesquisa.getText().toUpperCase();
        if (text.length() == 0)
        {
             sorter.setRowFilter(null);
        }
        else
        {
             try
             {
                   sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text,1));
             }
             catch (PatternSyntaxException pse)
             {
                   System.err.println("Erro");
             }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_edtPesquisaKeyPressed

    private void edtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtValorActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      baixar();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int linhaSelecionada = -1;
    int id=0;
        ContasPagar conta = new ContasPagar();
        linhaSelecionada = tabelaContas.getSelectedRow();
        if (linhaSelecionada >= 0) { 
            id = (int) tabelaContas.getValueAt(linhaSelecionada, 0);
            ContasPagarBD bd = new ContasPagarBD();
            conta = bd.getContasPagarById(id);
            if(conta.getSituacao()==1){
            relatorio(id);
            }else{
                int resposta = JOptionPane.showConfirmDialog(this, "A Conta Selecionada não se encontra paga\n Deseja realizar baixa e prosseguir com a  impressão? ","Atenção!",JOptionPane.YES_NO_OPTION);
                if(resposta==JOptionPane.YES_OPTION){
                  conta.setSituacao(1);
                    try {
                        bd.AtualizaConta(conta);
                        preencheTabela();
                    } catch (Exception ex) {
                        Logger.getLogger(FormContasPagar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    relatorio(conta.getId());
                }
            }
        }else{
        JOptionPane.showMessageDialog(this, "Selecione Uma linha na Tabela Para Gerar Recibo.");
    }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      FormRelatorioContasPagar form = new FormRelatorioContasPagar();
      form.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
private void relatorio(int id){
    InputStream inputStream = getClass().getResourceAsStream("/Relatorios/ReciboConta.jasper");
        Map parametros = new HashMap();
        parametros.put("id", id);
       

        try {
            ConectionSingleton conexaosingleton = ConectionSingleton.getInstancia();
            Connection connection = conexaosingleton.conectar();

            // abre o relatório
            ReportUtilsDireto.openReport( "Venda", inputStream, parametros, connection);
           // FormProgressDialogDireto pro = new FormProgressDialogDireto("Venda", inputStream, parametros,
                   // connection);

        } catch (SQLException exc) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro" + exc );
        } catch (JRException exc) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "erro" + exc);
        } catch (Exception ex) {
//            Logger.getLogger(TelaInicial.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "erro" + ex);
        }
    JOptionPane.showMessageDialog(this, "Recibo Impresso com sucesso.");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormContasPagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormContasPagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PanelGuia;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JComboBox<String> comboSituacao;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextField edtDescricao;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JTextField edtValor;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabelaContas;
    // End of variables declaration//GEN-END:variables

    private ContasPagar preencheContas() {
        ContasPagar contas = new ContasPagar();
        if (edtValor.getText().isEmpty()==false && edtDescricao.getText().isEmpty()==false && jDate.getDate()!=null) {
           
            contas.setValor(Double.valueOf(edtValor.getText()));
            contas.setDescricao(edtDescricao.getText());
            contas.setSituacao(comboSituacao.getSelectedIndex());
            
            java.sql.Date dataSql = new java.sql.Date(jDate.getDate().getTime());
            contas.setData(dataSql);
        }
        return contas;
    }

    private void preencheTabela() {
        ContasPagarBD bd = new ContasPagarBD();
    try {
        lista= bd.getListaContasPagar();
    } catch (Exception ex) {
        Logger.getLogger(FormContasPagar.class.getName()).log(Level.SEVERE, null, ex);
    }
        TabelaContasPagar model = new TabelaContasPagar(lista);
        tabelaContas.setModel(model);
    
    
    
    
    }
    private void preencheTabelaAberto() {
        ContasPagarBD bd = new ContasPagarBD();
    try {
        lista= bd.getListaContasPagarAberto();
    } catch (Exception ex) {
        Logger.getLogger(FormContasPagar.class.getName()).log(Level.SEVERE, null, ex);
    }
        TabelaContasPagar model = new TabelaContasPagar(lista);
        tabelaContas.setModel(model);
    
    
    
    
    }
}
