/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.ConfiguracaoBD;
import Conection.GrupoUsuarioBD;
import Objetos.Cliente;
import Objetos.Configuracao;
import Objetos.Funcionario;
import Objetos.GrupoUsuario;
import ferramentas.TabelaGrupoUsuario;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class FormConfSistema extends javax.swing.JFrame {
     
  
    GrupoUsuario grupoUsuario = null ;
    Configuracao configuracao = null;
    Funcionario funcionario = null;
    Cliente cliente = null;
    
    public FormConfSistema() {
        initComponents();
       preencheTableGrupoUsuarios();
       grupoUsuario= new GrupoUsuario();
        try {
            configuracao = ConfiguracaoBD.getInstancia();
        } catch (Exception ex) {
            Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(configuracao!=null){
tela();
    }
    }
    
    private void tela(){
        cContapagar.setSelected(configuracao.getContasaPagar());
        cContareceber.setSelected(configuracao.getContasaReceber());
        cProdutosEstoqueMin.setSelected(configuracao.getProdutosEstoqueMinimo());
        cValorCaixa.setSelected(configuracao.getValorCaixa());
        
        cCartao.setSelected(configuracao.getCartao());
        cCheque.setSelected(configuracao.getCheque());
        cDinheiro.setSelected(configuracao.getDinheiro());
        cNotinha.setSelected(configuracao.getNotinha());
        
        colorFundoCancelado.setColor(new Color(Integer.valueOf(configuracao.getCorFundoCancelado())));
        colorFundoCondicional.setColor(new Color(Integer.valueOf(configuracao.getCorFundoCondicional())));
        colorFundoNormal.setColor(new Color(Integer.valueOf(configuracao.getCorFundoNormal())));
        
        colorletraCancelado.setColor(new Color(Integer.valueOf(configuracao.getCorLetrasCancelado())));
        colorletraCondicional.setColor(new Color(Integer.valueOf(configuracao.getCorLetrasCondicional())));
        colorletraNormal.setColor(new Color(Integer.valueOf(configuracao.getCorLetrasNormal())));
        
        colorGeralFundo.setColor(new Color(Integer.valueOf(configuracao.getCorGeralFundo())));
        colorGeralLetra.setColor(new Color(Integer.valueOf(configuracao.getCorGeralLetra())));
        
        
    }
private void preencheTableGrupoUsuarios(){
        try {
            List<GrupoUsuario> lista = new GrupoUsuarioBD().getGrupos();
            TabelaGrupoUsuario tabelaGrupoUsuario = new TabelaGrupoUsuario(lista);
            tableGrupoUsuarios.setModel(tabelaGrupoUsuario);
        } catch (Exception ex) {
            Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        corGeralFundo = new javax.swing.JFrame();
        colorGeralFundo = new javax.swing.JColorChooser();
        btnGeralFundoOk = new javax.swing.JButton();
        corGeralLetra = new javax.swing.JFrame();
        colorGeralLetra = new javax.swing.JColorChooser();
        btnGeralLetra = new javax.swing.JButton();
        corLetraCancelado = new javax.swing.JFrame();
        colorletraCancelado = new javax.swing.JColorChooser();
        btnLetraCancelado = new javax.swing.JButton();
        corLetraCondicional = new javax.swing.JFrame();
        colorletraCondicional = new javax.swing.JColorChooser();
        btnLetraCondicional = new javax.swing.JButton();
        corLetraNormal = new javax.swing.JFrame();
        colorletraNormal = new javax.swing.JColorChooser();
        btnLetraNormal = new javax.swing.JButton();
        corFundoCancelado = new javax.swing.JFrame();
        colorFundoCancelado = new javax.swing.JColorChooser();
        btnFundoCancelado = new javax.swing.JButton();
        corFundoCondicional = new javax.swing.JFrame();
        colorFundoCondicional = new javax.swing.JColorChooser();
        btnFundoCondicional = new javax.swing.JButton();
        corFundoNormal = new javax.swing.JFrame();
        colorFundoNormal = new javax.swing.JColorChooser();
        btnFundoNormal = new javax.swing.JButton();
        frameGruposUsuarios = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        cCadCliente = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        edtNomeGrupo = new javax.swing.JTextField();
        cCadProduto = new javax.swing.JCheckBox();
        cCadFornecedor = new javax.swing.JCheckBox();
        cCadEmpresa = new javax.swing.JCheckBox();
        cCadFuncionario = new javax.swing.JCheckBox();
        cCadServico = new javax.swing.JCheckBox();
        cCaixa = new javax.swing.JCheckBox();
        cContasAPagar = new javax.swing.JCheckBox();
        cContasAReceber = new javax.swing.JCheckBox();
        cVenda = new javax.swing.JCheckBox();
        cOs = new javax.swing.JCheckBox();
        cRelatorio = new javax.swing.JCheckBox();
        cConfiguracao = new javax.swing.JCheckBox();
        cCadContaContabil = new javax.swing.JCheckBox();
        btnSalvarGrupo = new javax.swing.JButton();
        btnCancelarGrupo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cContapagar = new javax.swing.JCheckBox();
        cContareceber = new javax.swing.JCheckBox();
        cProdutosEstoqueMin = new javax.swing.JCheckBox();
        cValorCaixa = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCorDeFundo = new javax.swing.JButton();
        btnCorGeralLetra = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLetraStatusCancelado = new javax.swing.JButton();
        btnLetraStatusCondicional = new javax.swing.JButton();
        btnLetraStatusNormal = new javax.swing.JButton();
        btnFundoStatusCancelado = new javax.swing.JButton();
        btnFundoStatusCondicional = new javax.swing.JButton();
        btnFundoStatusNormal = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrupoUsuarios = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        cDinheiro = new javax.swing.JCheckBox();
        cCartao = new javax.swing.JCheckBox();
        cCheque = new javax.swing.JCheckBox();
        cNotinha = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        edtVendedor = new javax.swing.JTextField();
        edtCliente = new javax.swing.JTextField();

        corGeralFundo.setBackground(new java.awt.Color(255, 255, 255));

        btnGeralFundoOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnGeralFundoOk.setText("Pronto");
        btnGeralFundoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeralFundoOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corGeralFundoLayout = new javax.swing.GroupLayout(corGeralFundo.getContentPane());
        corGeralFundo.getContentPane().setLayout(corGeralFundoLayout);
        corGeralFundoLayout.setHorizontalGroup(
            corGeralFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corGeralFundoLayout.createSequentialGroup()
                .addComponent(colorGeralFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corGeralFundoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeralFundoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corGeralFundoLayout.setVerticalGroup(
            corGeralFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corGeralFundoLayout.createSequentialGroup()
                .addComponent(colorGeralFundo, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnGeralFundoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnGeralLetra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnGeralLetra.setText("Pronto");
        btnGeralLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeralLetraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corGeralLetraLayout = new javax.swing.GroupLayout(corGeralLetra.getContentPane());
        corGeralLetra.getContentPane().setLayout(corGeralLetraLayout);
        corGeralLetraLayout.setHorizontalGroup(
            corGeralLetraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corGeralLetraLayout.createSequentialGroup()
                .addComponent(colorGeralLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corGeralLetraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeralLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corGeralLetraLayout.setVerticalGroup(
            corGeralLetraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corGeralLetraLayout.createSequentialGroup()
                .addComponent(colorGeralLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnGeralLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnLetraCancelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnLetraCancelado.setText("Pronto");
        btnLetraCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetraCanceladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corLetraCanceladoLayout = new javax.swing.GroupLayout(corLetraCancelado.getContentPane());
        corLetraCancelado.getContentPane().setLayout(corLetraCanceladoLayout);
        corLetraCanceladoLayout.setHorizontalGroup(
            corLetraCanceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corLetraCanceladoLayout.createSequentialGroup()
                .addComponent(colorletraCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corLetraCanceladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLetraCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corLetraCanceladoLayout.setVerticalGroup(
            corLetraCanceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corLetraCanceladoLayout.createSequentialGroup()
                .addComponent(colorletraCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnLetraCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnLetraCondicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnLetraCondicional.setText("Pronto");
        btnLetraCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetraCondicionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corLetraCondicionalLayout = new javax.swing.GroupLayout(corLetraCondicional.getContentPane());
        corLetraCondicional.getContentPane().setLayout(corLetraCondicionalLayout);
        corLetraCondicionalLayout.setHorizontalGroup(
            corLetraCondicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corLetraCondicionalLayout.createSequentialGroup()
                .addComponent(colorletraCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corLetraCondicionalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLetraCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corLetraCondicionalLayout.setVerticalGroup(
            corLetraCondicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corLetraCondicionalLayout.createSequentialGroup()
                .addComponent(colorletraCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnLetraCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnLetraNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnLetraNormal.setText("Pronto");
        btnLetraNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetraNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corLetraNormalLayout = new javax.swing.GroupLayout(corLetraNormal.getContentPane());
        corLetraNormal.getContentPane().setLayout(corLetraNormalLayout);
        corLetraNormalLayout.setHorizontalGroup(
            corLetraNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corLetraNormalLayout.createSequentialGroup()
                .addComponent(colorletraNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corLetraNormalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLetraNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corLetraNormalLayout.setVerticalGroup(
            corLetraNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corLetraNormalLayout.createSequentialGroup()
                .addComponent(colorletraNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnLetraNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnFundoCancelado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnFundoCancelado.setText("Pronto");
        btnFundoCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundoCanceladoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corFundoCanceladoLayout = new javax.swing.GroupLayout(corFundoCancelado.getContentPane());
        corFundoCancelado.getContentPane().setLayout(corFundoCanceladoLayout);
        corFundoCanceladoLayout.setHorizontalGroup(
            corFundoCanceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corFundoCanceladoLayout.createSequentialGroup()
                .addComponent(colorFundoCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corFundoCanceladoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFundoCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corFundoCanceladoLayout.setVerticalGroup(
            corFundoCanceladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corFundoCanceladoLayout.createSequentialGroup()
                .addComponent(colorFundoCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnFundoCancelado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnFundoCondicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnFundoCondicional.setText("Pronto");
        btnFundoCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundoCondicionalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corFundoCondicionalLayout = new javax.swing.GroupLayout(corFundoCondicional.getContentPane());
        corFundoCondicional.getContentPane().setLayout(corFundoCondicionalLayout);
        corFundoCondicionalLayout.setHorizontalGroup(
            corFundoCondicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corFundoCondicionalLayout.createSequentialGroup()
                .addComponent(colorFundoCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corFundoCondicionalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFundoCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corFundoCondicionalLayout.setVerticalGroup(
            corFundoCondicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corFundoCondicionalLayout.createSequentialGroup()
                .addComponent(colorFundoCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnFundoCondicional, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        btnFundoNormal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirmar (1).png"))); // NOI18N
        btnFundoNormal.setText("Pronto");
        btnFundoNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundoNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout corFundoNormalLayout = new javax.swing.GroupLayout(corFundoNormal.getContentPane());
        corFundoNormal.getContentPane().setLayout(corFundoNormalLayout);
        corFundoNormalLayout.setHorizontalGroup(
            corFundoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corFundoNormalLayout.createSequentialGroup()
                .addComponent(colorFundoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corFundoNormalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFundoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        corFundoNormalLayout.setVerticalGroup(
            corFundoNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corFundoNormalLayout.createSequentialGroup()
                .addComponent(colorFundoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 293, Short.MAX_VALUE)
                .addGap(5, 5, 5)
                .addComponent(btnFundoNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        frameGruposUsuarios.setTitle("Grupo de Usuarios");
        frameGruposUsuarios.setResizable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        cCadCliente.setBackground(new java.awt.Color(255, 255, 255));
        cCadCliente.setText("Cadastro de Clientes");

        jLabel9.setText("Nome:");

        cCadProduto.setBackground(new java.awt.Color(255, 255, 255));
        cCadProduto.setText("Cadastro de Produtos");

        cCadFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        cCadFornecedor.setText("Cadastro de Fornecedores");
        cCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCadFornecedorActionPerformed(evt);
            }
        });

        cCadEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cCadEmpresa.setText("Cadastro de Empresa");

        cCadFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        cCadFuncionario.setText("Cadastro de Funcionario");

        cCadServico.setBackground(new java.awt.Color(255, 255, 255));
        cCadServico.setText("Cadastro de Serviço");

        cCaixa.setBackground(new java.awt.Color(255, 255, 255));
        cCaixa.setText("Caixa");

        cContasAPagar.setBackground(new java.awt.Color(255, 255, 255));
        cContasAPagar.setText("Contas a pagar");

        cContasAReceber.setBackground(new java.awt.Color(255, 255, 255));
        cContasAReceber.setText("Contas a Receber");

        cVenda.setBackground(new java.awt.Color(255, 255, 255));
        cVenda.setText("Venda");

        cOs.setBackground(new java.awt.Color(255, 255, 255));
        cOs.setText("Ordem de Serviço");

        cRelatorio.setBackground(new java.awt.Color(255, 255, 255));
        cRelatorio.setText("Relatorios");

        cConfiguracao.setBackground(new java.awt.Color(255, 255, 255));
        cConfiguracao.setText("Configuração do Sistema");

        cCadContaContabil.setBackground(new java.awt.Color(255, 255, 255));
        cCadContaContabil.setText("Cadastro de Conta Contabil");

        btnSalvarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/confirma.png"))); // NOI18N
        btnSalvarGrupo.setText("Salvar");
        btnSalvarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarGrupoActionPerformed(evt);
            }
        });

        btnCancelarGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelarGrupo.setText("Cancelar");
        btnCancelarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cCadCliente)
                    .addComponent(cCadProduto)
                    .addComponent(cCadFornecedor)
                    .addComponent(cCadEmpresa)
                    .addComponent(cCadFuncionario)
                    .addComponent(cCadServico)
                    .addComponent(cCadContaContabil))
                .addGap(108, 108, 108)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cConfiguracao)
                    .addComponent(cRelatorio)
                    .addComponent(cOs)
                    .addComponent(cVenda)
                    .addComponent(cContasAReceber)
                    .addComponent(cContasAPagar)
                    .addComponent(cCaixa))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnSalvarGrupo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarGrupo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cCadCliente, cCadContaContabil, cCadEmpresa, cCadFornecedor, cCadFuncionario, cCadProduto, cCadServico, cCaixa, cConfiguracao, cContasAPagar, cContasAReceber, cOs, cRelatorio, cVenda});

        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edtNomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCadCliente)
                    .addComponent(cCaixa))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCadProduto)
                    .addComponent(cContasAPagar))
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCadFornecedor)
                    .addComponent(cContasAReceber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCadEmpresa)
                    .addComponent(cVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCadFuncionario)
                    .addComponent(cOs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCadServico)
                    .addComponent(cRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCadContaContabil)
                    .addComponent(cConfiguracao))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarGrupo)
                    .addComponent(btnCancelarGrupo))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cCadCliente, cCadContaContabil, cCadEmpresa, cCadFornecedor, cCadFuncionario, cCadProduto, cCadServico, cCaixa, cConfiguracao, cContasAPagar, cContasAReceber, cOs, cRelatorio, cVenda});

        javax.swing.GroupLayout frameGruposUsuariosLayout = new javax.swing.GroupLayout(frameGruposUsuarios.getContentPane());
        frameGruposUsuarios.getContentPane().setLayout(frameGruposUsuariosLayout);
        frameGruposUsuariosLayout.setHorizontalGroup(
            frameGruposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameGruposUsuariosLayout.setVerticalGroup(
            frameGruposUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ativar/Desativar Lembretes Tela Inicial"));

        cContapagar.setBackground(new java.awt.Color(255, 255, 255));
        cContapagar.setText("Contas a pagar");

        cContareceber.setBackground(new java.awt.Color(255, 255, 255));
        cContareceber.setText("Contas a receber");

        cProdutosEstoqueMin.setBackground(new java.awt.Color(255, 255, 255));
        cProdutosEstoqueMin.setText("Produtos com estoque minimo");

        cValorCaixa.setBackground(new java.awt.Color(255, 255, 255));
        cValorCaixa.setText("Valor em caixa");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cContapagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cContareceber, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addComponent(cProdutosEstoqueMin)
                    .addComponent(cValorCaixa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cContapagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cContareceber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cProdutosEstoqueMin)
                .addGap(0, 0, 0)
                .addComponent(cValorCaixa)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cores Do Sistema"));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Geral"));

        jLabel1.setText("Cor de fundo:");

        jLabel2.setText("Cor da letra:");

        btnCorDeFundo.setText("Selecione");
        btnCorDeFundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorDeFundoActionPerformed(evt);
            }
        });

        btnCorGeralLetra.setText("Selecione");
        btnCorGeralLetra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorGeralLetraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCorDeFundo))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCorGeralLetra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCorDeFundo))
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCorGeralLetra))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabelas"));

        jLabel3.setText("Cor letras status cancelado:");

        jLabel4.setText("Cor de fundo status cancelado:");

        jLabel5.setText("Cor letras condicional:");

        jLabel6.setText("Cor de fundo condicional:");

        jLabel7.setText("Cor letras normal:");

        jLabel8.setText("Cor de fundo normal:");

        btnLetraStatusCancelado.setText("Selecione");
        btnLetraStatusCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetraStatusCanceladoActionPerformed(evt);
            }
        });

        btnLetraStatusCondicional.setText("Selecione");
        btnLetraStatusCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetraStatusCondicionalActionPerformed(evt);
            }
        });

        btnLetraStatusNormal.setText("Selecione");
        btnLetraStatusNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLetraStatusNormalActionPerformed(evt);
            }
        });

        btnFundoStatusCancelado.setText("Selecione");
        btnFundoStatusCancelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundoStatusCanceladoActionPerformed(evt);
            }
        });

        btnFundoStatusCondicional.setText("Selecione");
        btnFundoStatusCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundoStatusCondicionalActionPerformed(evt);
            }
        });

        btnFundoStatusNormal.setText("Selecione");
        btnFundoStatusNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFundoStatusNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLetraStatusNormal)
                    .addComponent(btnLetraStatusCondicional)
                    .addComponent(btnLetraStatusCancelado))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFundoStatusNormal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFundoStatusCondicional))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFundoStatusCancelado)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnLetraStatusCancelado)
                    .addComponent(btnFundoStatusCancelado))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(btnLetraStatusCondicional)
                    .addComponent(btnFundoStatusCondicional))
                .addGap(0, 0, 0)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(btnLetraStatusNormal)
                    .addComponent(btnFundoStatusNormal)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jButton10.setText("Restaurar padrão");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Salvar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Cancelar");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupos de Usuarios"));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        tableGrupoUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableGrupoUsuarios);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lixeira.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.gif"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton13)
                .addGap(18, 18, 18)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addGap(2, 2, 2))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton13, jButton14, jButton15});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton13)))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton13, jButton14, jButton15});

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas de Pagamento"));

        cDinheiro.setBackground(new java.awt.Color(255, 255, 255));
        cDinheiro.setText("Dinheiro");

        cCartao.setBackground(new java.awt.Color(255, 255, 255));
        cCartao.setText("Cartão");

        cCheque.setBackground(new java.awt.Color(255, 255, 255));
        cCheque.setText("Cheque");

        cNotinha.setBackground(new java.awt.Color(255, 255, 255));
        cNotinha.setText("Notinha");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cCheque)
                    .addComponent(cCartao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cDinheiro)
                    .addComponent(cNotinha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCartao)
                    .addComponent(cDinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCheque)
                    .addComponent(cNotinha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Padrões"));

        jLabel10.setText("Vendedor Padrão:");

        jLabel11.setText("Cliente Padrão:");

        edtVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtVendedorKeyPressed(evt);
            }
        });

        edtCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtClienteKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(edtCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(edtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(edtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton10, jButton11, jButton12});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton10, jButton11, jButton12});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorDeFundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorDeFundoActionPerformed
        formColor(corGeralFundo);
    }//GEN-LAST:event_btnCorDeFundoActionPerformed

    private void btnCorGeralLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorGeralLetraActionPerformed
        formColor(corGeralLetra);
    }//GEN-LAST:event_btnCorGeralLetraActionPerformed

    private void btnLetraStatusCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetraStatusCanceladoActionPerformed
        formColor(corLetraCancelado);
    }//GEN-LAST:event_btnLetraStatusCanceladoActionPerformed

    private void btnLetraStatusCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetraStatusCondicionalActionPerformed
        formColor(corLetraCondicional);
    }//GEN-LAST:event_btnLetraStatusCondicionalActionPerformed

    private void btnLetraStatusNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetraStatusNormalActionPerformed
        formColor(corLetraNormal);
    }//GEN-LAST:event_btnLetraStatusNormalActionPerformed

    private void btnFundoStatusCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundoStatusCanceladoActionPerformed
        formColor(corFundoCancelado);
    }//GEN-LAST:event_btnFundoStatusCanceladoActionPerformed

    private void btnFundoStatusCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundoStatusCondicionalActionPerformed
        formColor(corFundoCondicional);
    }//GEN-LAST:event_btnFundoStatusCondicionalActionPerformed

    private void btnFundoStatusNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundoStatusNormalActionPerformed
        formColor(corFundoNormal);
    }//GEN-LAST:event_btnFundoStatusNormalActionPerformed

    private void btnGeralFundoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeralFundoOkActionPerformed
      
        corGeralFundo.dispose();
       // btnCorDeFundo.setBackground(new Color(Integer.valueOf(cor)));
    }//GEN-LAST:event_btnGeralFundoOkActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       frameGruposUsuarios.setMinimumSize(new Dimension(500, 300));
        frameGruposUsuarios.setLocationRelativeTo(null);
        frameGruposUsuarios.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void cCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCadFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCadFornecedorActionPerformed

    private void btnSalvarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarGrupoActionPerformed
        GrupoUsuarioBD bD = new GrupoUsuarioBD();
        if (edtNomeGrupo.getText().isEmpty() == false) {
                grupoUsuario = preencheGrupo();
                if (grupoUsuario.getId() > 0) {
                    try {
                    //atualiza
                    bD.updateGrupoUsuario(grupoUsuario);
                      JOptionPane.showMessageDialog(this, "Sucesso ao Atualizar Grupo");
                    } catch (Exception ex) {
                        Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "Erro ao Atualizar Grupo");
                    }
                } else {
                    try {
                    //insere
                    bD.adicionarGrupoUsuario(grupoUsuario);
                    JOptionPane.showMessageDialog(this, "Sucesso ao inserir Grupo");
                    } catch (Exception ex) {
                        Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "erro ao inserir Grupo");
                    }
                }
        } else {
            JOptionPane.showMessageDialog(this, "Nome do Grupo não pode estar vazio.");
        }
           preencheTableGrupoUsuarios();
        frameGruposUsuarios.dispose();
     
    }//GEN-LAST:event_btnSalvarGrupoActionPerformed

    private void btnCancelarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGrupoActionPerformed
        frameGruposUsuarios.dispose();
    }//GEN-LAST:event_btnCancelarGrupoActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
int id = pegaSelecionado().getId();
int resultado = JOptionPane.showConfirmDialog(this, "Confirma Exclusão?","Confirma Exclusão?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
if(resultado==JOptionPane.YES_OPTION){
    new GrupoUsuarioBD().deletarGrupo(id);
    JOptionPane.showMessageDialog(this, "Grupo Excluido com sucesso.");
    preencheTableGrupoUsuarios();
}
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
      this.grupoUsuario = pegaSelecionado();
        System.out.println("id Grupo"+grupoUsuario.getId());
          edtNomeGrupo.setText(grupoUsuario.getNome());
          frameGruposUsuarios.setMinimumSize(new Dimension(500, 300));
        frameGruposUsuarios.setLocationRelativeTo(null);
        frameGruposUsuarios.setVisible(true);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      ConfiguracaoBD bd = new ConfiguracaoBD();
        if(configuracao==null){
            configuracao= new Configuracao();
        }
        configuracao.setCartao(cCartao.isSelected());
        configuracao.setCheque(cCheque.isSelected());
        configuracao.setDinheiro(cDinheiro.isSelected());
        configuracao.setNotinha(cNotinha.isSelected());
        
        configuracao.setValorCaixa(cValorCaixa.isSelected());
        configuracao.setContasaPagar(cContapagar.isSelected());
        configuracao.setContasaReceber(cContareceber.isSelected());
        configuracao.setProdutosEstoqueMinimo(cProdutosEstoqueMin.isSelected());
        
        
        configuracao.setCorGeralFundo(String.valueOf(colorGeralFundo.getColor().getRGB()));
        configuracao.setCorGeralLetra(String.valueOf(colorGeralLetra.getColor().getRGB()));
        
        configuracao.setCorFundoCancelado(String.valueOf(colorFundoCancelado.getColor().getRGB()));
        configuracao.setCorFundoCondicional(String.valueOf(colorFundoCondicional.getColor().getRGB()));
        configuracao.setCorFundoNormal(String.valueOf(colorFundoNormal.getColor().getRGB()));
        
        configuracao.setCorLetrasCancelado(String.valueOf(colorletraCancelado.getColor().getRGB()));
        configuracao.setCorLetrasCondicional(String.valueOf(colorletraCondicional.getColor().getRGB()));
        configuracao.setCorLetrasNormal(String.valueOf(colorletraNormal.getColor().getRGB()));
        
        if(configuracao.getId()>0){
          try {
              bd.updateConfiguracao(configuracao);
              JOptionPane.showMessageDialog(this, "Sucesso ao atualizar configurações");
          } catch (Exception ex) {
              Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this, "erro ao atualizar configurações");
          }
        }else{
          try {
              bd.adicionarConfiguracao(configuracao);
              JOptionPane.showMessageDialog(this, "Sucesso ao adicionar configurações");
          } catch (Exception ex) {
              Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this, "erro ao adicionar configurações");
          }
        }
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
        // restaurar padroes
        
        ConfiguracaoBD bd = new ConfiguracaoBD();
        if(configuracao==null){
            configuracao= new Configuracao();
        }
        configuracao.setCartao(true);
        configuracao.setCheque(true);
        configuracao.setDinheiro(true);
        configuracao.setNotinha(true);
        
        configuracao.setValorCaixa(false);
        configuracao.setContasaPagar(false);
        configuracao.setContasaReceber(false);
        configuracao.setProdutosEstoqueMinimo(false);
        
        
        configuracao.setCorGeralFundo(String.valueOf(new Color(255, 255, 255).getRGB()));
        configuracao.setCorGeralLetra(String.valueOf(new Color(0, 0, 0).getRGB()));
        
        configuracao.setCorFundoCancelado(String.valueOf(new Color(255, 153, 159).getRGB()));
        configuracao.setCorFundoCondicional(String.valueOf(new Color(204, 204, 255).getRGB()));
        configuracao.setCorFundoNormal(String.valueOf(new Color(255, 255, 255).getRGB()));
        
        configuracao.setCorLetrasCancelado(String.valueOf(new Color(255, 255, 255).getRGB()));
        configuracao.setCorLetrasCondicional(String.valueOf(new Color(255, 255, 255).getRGB()));
        configuracao.setCorLetrasNormal(String.valueOf(new Color(0, 0, 0).getRGB()));
        
        if(configuracao.getId()>0){
          try {
              bd.updateConfiguracao(configuracao);
              JOptionPane.showMessageDialog(this, "Sucesso ao atualizar configurações");
          } catch (Exception ex) {
              Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this, "erro ao atualizar configurações");
          }
        }else{
          try {
              bd.adicionarConfiguracao(configuracao);
              JOptionPane.showMessageDialog(this, "Sucesso ao adicionar configurações");
          } catch (Exception ex) {
              Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
              JOptionPane.showMessageDialog(this, "erro ao adicionar configurações");
          }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnGeralLetraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeralLetraActionPerformed
        corGeralLetra.dispose();
    }//GEN-LAST:event_btnGeralLetraActionPerformed

    private void btnLetraCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetraCanceladoActionPerformed
       corLetraCancelado.dispose();
    }//GEN-LAST:event_btnLetraCanceladoActionPerformed

    private void btnLetraCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetraCondicionalActionPerformed
        corLetraCondicional.dispose();
    }//GEN-LAST:event_btnLetraCondicionalActionPerformed

    private void btnLetraNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLetraNormalActionPerformed
        corLetraNormal.dispose();
    }//GEN-LAST:event_btnLetraNormalActionPerformed

    private void btnFundoCanceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundoCanceladoActionPerformed
        corFundoCancelado.dispose();
    }//GEN-LAST:event_btnFundoCanceladoActionPerformed

    private void btnFundoCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundoCondicionalActionPerformed
       corFundoCondicional.dispose();
    }//GEN-LAST:event_btnFundoCondicionalActionPerformed

    private void btnFundoNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFundoNormalActionPerformed
       corFundoNormal.dispose();
    }//GEN-LAST:event_btnFundoNormalActionPerformed

    private void edtVendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtVendedorKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_F8 || evt.getKeyCode() == KeyEvent.VK_ENTER ){
           FormSelecionaFuncionario form = new  FormSelecionaFuncionario(this);
           form.setVisible(true);
       }
    }//GEN-LAST:event_edtVendedorKeyPressed

    private void edtClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtClienteKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_F8 || evt.getKeyCode() == KeyEvent.VK_ENTER ){
           FormSelecionaCliente form = new  FormSelecionaCliente(this);
           form.setVisible(true);
       }
    }//GEN-LAST:event_edtClienteKeyPressed

    
    private GrupoUsuario pegaSelecionado(){
     int linhaSelecionada = -1;
        GrupoUsuario grupo= null;
        linhaSelecionada = tableGrupoUsuarios.getSelectedRow();
        if (linhaSelecionada >= 0) { 
            int idGrupo = (int) tableGrupoUsuarios.getValueAt(linhaSelecionada, 0);
          
            
         try {
             grupo= new GrupoUsuarioBD().getGruposById(idGrupo);
         } catch (Exception ex) {
             Logger.getLogger(FormConfSistema.class.getName()).log(Level.SEVERE, null, ex);
         }
}else{
           JOptionPane.showMessageDialog(this, "É necessario selecionar uma linha.");
        }
        
        return grupo;
}
    private void formColor(JFrame jFrame) {
        jFrame.setMinimumSize(new Dimension(650, 400));
        jFrame.setLocationRelativeTo(null);
        jFrame.setVisible(true);
    }
private GrupoUsuario preencheGrupo(){

    
    grupoUsuario.setNome(edtNomeGrupo.getText());
    grupoUsuario.setCadCliente(cCadCliente.isSelected());
    grupoUsuario.setCadEmpresa(cCadEmpresa.isSelected()); 
    grupoUsuario.setCadFornecedor(cCadFornecedor.isSelected());
    grupoUsuario.setCadFuncionario(cCadFuncionario.isSelected());
    grupoUsuario.setCadProduto(cCadProduto.isSelected());
    grupoUsuario.setCadServico(cCadServico.isSelected());
    grupoUsuario.setCaixa(cCaixa.isSelected());
    grupoUsuario.setConfiguracao(cConfiguracao.isSelected());
    grupoUsuario.setContaContabil(cCadContaContabil.isSelected());
    grupoUsuario.setContaPagar(cContasAPagar.isSelected());
    grupoUsuario.setContaReceber(cContasAReceber.isSelected());
    grupoUsuario.setOs(cOs.isSelected());
    grupoUsuario.setRelatorio(cRelatorio.isSelected());
    grupoUsuario.setVenda(cVenda.isSelected());
    
    return grupoUsuario;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConfSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConfSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConfSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConfSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormConfSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarGrupo;
    private javax.swing.JButton btnCorDeFundo;
    private javax.swing.JButton btnCorGeralLetra;
    private javax.swing.JButton btnFundoCancelado;
    private javax.swing.JButton btnFundoCondicional;
    private javax.swing.JButton btnFundoNormal;
    private javax.swing.JButton btnFundoStatusCancelado;
    private javax.swing.JButton btnFundoStatusCondicional;
    private javax.swing.JButton btnFundoStatusNormal;
    private javax.swing.JButton btnGeralFundoOk;
    private javax.swing.JButton btnGeralLetra;
    private javax.swing.JButton btnLetraCancelado;
    private javax.swing.JButton btnLetraCondicional;
    private javax.swing.JButton btnLetraNormal;
    private javax.swing.JButton btnLetraStatusCancelado;
    private javax.swing.JButton btnLetraStatusCondicional;
    private javax.swing.JButton btnLetraStatusNormal;
    private javax.swing.JButton btnSalvarGrupo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cCadCliente;
    private javax.swing.JCheckBox cCadContaContabil;
    private javax.swing.JCheckBox cCadEmpresa;
    private javax.swing.JCheckBox cCadFornecedor;
    private javax.swing.JCheckBox cCadFuncionario;
    private javax.swing.JCheckBox cCadProduto;
    private javax.swing.JCheckBox cCadServico;
    private javax.swing.JCheckBox cCaixa;
    private javax.swing.JCheckBox cCartao;
    private javax.swing.JCheckBox cCheque;
    private javax.swing.JCheckBox cConfiguracao;
    private javax.swing.JCheckBox cContapagar;
    private javax.swing.JCheckBox cContareceber;
    private javax.swing.JCheckBox cContasAPagar;
    private javax.swing.JCheckBox cContasAReceber;
    private javax.swing.JCheckBox cDinheiro;
    private javax.swing.JCheckBox cNotinha;
    private javax.swing.JCheckBox cOs;
    private javax.swing.JCheckBox cProdutosEstoqueMin;
    private javax.swing.JCheckBox cRelatorio;
    private javax.swing.JCheckBox cValorCaixa;
    private javax.swing.JCheckBox cVenda;
    private javax.swing.JColorChooser colorFundoCancelado;
    private javax.swing.JColorChooser colorFundoCondicional;
    private javax.swing.JColorChooser colorFundoNormal;
    private javax.swing.JColorChooser colorGeralFundo;
    private javax.swing.JColorChooser colorGeralLetra;
    private javax.swing.JColorChooser colorletraCancelado;
    private javax.swing.JColorChooser colorletraCondicional;
    private javax.swing.JColorChooser colorletraNormal;
    private javax.swing.JFrame corFundoCancelado;
    private javax.swing.JFrame corFundoCondicional;
    private javax.swing.JFrame corFundoNormal;
    private javax.swing.JFrame corGeralFundo;
    private javax.swing.JFrame corGeralLetra;
    private javax.swing.JFrame corLetraCancelado;
    private javax.swing.JFrame corLetraCondicional;
    private javax.swing.JFrame corLetraNormal;
    private javax.swing.JTextField edtCliente;
    private javax.swing.JTextField edtNomeGrupo;
    private javax.swing.JTextField edtVendedor;
    private javax.swing.JFrame frameGruposUsuarios;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGrupoUsuarios;
    // End of variables declaration//GEN-END:variables

    void retornaFuncionario(Funcionario funcionario) {
       this.funcionario= funcionario;
       edtVendedor.setText(funcionario.getNome());
       edtVendedor.setBackground(Color.WHITE);
        validate();
    }

    void retornaCliente(Cliente cliente) {
     this.cliente = cliente;
     edtCliente.setText(cliente.getNome());
     edtCliente.setBackground(Color.WHITE);
     validate();
    }
}
