/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.CaixaBD;
import Conection.CaixaDiarioBD;
import Conection.ConfiguracaoBD;
import Objetos.Caixa;
import Objetos.CaixaDiario;
import Objetos.Configuracao;
import Objetos.LancamentoCaixa;
import ferramentas.TabelaCaixaDiario;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FormCaixaDiario extends javax.swing.JFrame {
    TabelaCaixaDiario model;
    List<CaixaDiario> lista;
    CaixaDiarioBD bd ;
    Configuracao configuracao= null;
    Double total=0.0 ;
    Caixa caixa;
    CaixaBD caixabd;
    int ultimoidCaixa=0;
    /**
     * Creates new form FormCaixaDiario
     */
    public FormCaixaDiario() {
        initComponents();
        
      bd = new CaixaDiarioBD();
      caixabd= new CaixaBD();
        try {
            
            caixa=caixabd.getUltimoCaixaById(0);
            ultimoidCaixa=caixa.getId();
            lista=bd.getListaClasseCaixa();
            model = new TabelaCaixaDiario(lista);
        jTableCaixa.setModel(model);
        if(caixa.getStatus().equals("FECHADO")){
            System.out.println("Entrou");
            jButtonExcluirLancamento.setEnabled(false);
            jButtonFazerLancamento.setEnabled(false);
            jButtonFecharCaixa.setEnabled(false);
             edtValorInicial.setText("R$ "+caixa.getValoratual());
            jLabelStatus.setText("Caixa fechado!");
                  
        }else if(caixa.getStatus().equals("ABERTO")){
            edtValorInicial.setText("R$ "+caixa.getValorinicial());
            jButtonAbreCaixa.setEnabled(false);
         jLabelStatus.setText("Caixa Aberto - Aguardando Lançamentos"); 
         if(lista.isEmpty()==false){
            total = bd.getCaixaDiarioSoma();
            total=total+caixa.getValorinicial();
            edtTotal.setText("R$ "+total);
         }else{
             edtTotal.setText("R$ "+caixa.getValorinicial());
         }
         
        }
            
            
        } catch (Exception ex) {
            Logger.getLogger(FormCaixaDiario.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this,"Erro Ao Obter Dados " +ex);
        }
        
         try {
            configuracao = ConfiguracaoBD.getInstancia();
        } catch (Exception ex) {
            Logger.getLogger(FormGerenciaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
         panelBack.setBackground(new Color(Integer.valueOf(configuracao.getCorGeralFundo())));
           panelButton.setBackground(new Color(Integer.valueOf(configuracao.getCorGeralFundo())));
             panelButton1.setBackground(new Color(Integer.valueOf(configuracao.getCorGeralFundo())));
          panelButton2.setBackground(new Color(Integer.valueOf(configuracao.getCorGeralFundo())));
          panelValor.setBackground(new Color(Integer.valueOf(configuracao.getCorGeralFundo())));
          jTableCaixa.setBackground(new Color(Integer.valueOf(configuracao.getCorFundoNormal())));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBack = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabelStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCaixa = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCaixa = new javax.swing.JTable();
        panelButton = new javax.swing.JPanel();
        panelButton1 = new javax.swing.JPanel();
        jButtonAbreCaixa = new javax.swing.JButton();
        jButtonFecharCaixa = new javax.swing.JButton();
        panelButton2 = new javax.swing.JPanel();
        jButtonFazerLancamento = new javax.swing.JButton();
        jButtonExcluirLancamento = new javax.swing.JButton();
        panelValor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtValorInicial = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Caixa");
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setText("Status caixa");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStatus)
                .addContainerGap())
        );

        jTableCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCaixa);

        jTableCaixa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCaixa);

        panelButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 218, 218)));

        panelButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 218, 218)));

        jButtonAbreCaixa.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAbreCaixa.setText("Abrir caixa");
        jButtonAbreCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbreCaixaActionPerformed(evt);
            }
        });

        jButtonFecharCaixa.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFecharCaixa.setText("Fechar Caixa");
        jButtonFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButton1Layout = new javax.swing.GroupLayout(panelButton1);
        panelButton1.setLayout(panelButton1Layout);
        panelButton1Layout.setHorizontalGroup(
            panelButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAbreCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFecharCaixa)
                .addContainerGap())
        );
        panelButton1Layout.setVerticalGroup(
            panelButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFecharCaixa)
                    .addComponent(jButtonAbreCaixa))
                .addContainerGap())
        );

        panelButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 218, 218)));

        jButtonFazerLancamento.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFazerLancamento.setText("Realizar lançamento");
        jButtonFazerLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFazerLancamentoActionPerformed(evt);
            }
        });

        jButtonExcluirLancamento.setBackground(new java.awt.Color(204, 204, 204));
        jButtonExcluirLancamento.setText("Excluir lançamento");
        jButtonExcluirLancamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirLancamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButton2Layout = new javax.swing.GroupLayout(panelButton2);
        panelButton2.setLayout(panelButton2Layout);
        panelButton2Layout.setHorizontalGroup(
            panelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButton2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonFazerLancamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExcluirLancamento)
                .addContainerGap())
        );
        panelButton2Layout.setVerticalGroup(
            panelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButton2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFazerLancamento)
                    .addComponent(jButtonExcluirLancamento))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(panelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelValor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Valores")));

        jLabel1.setText("Atual:");

        jLabel2.setText("Inicial:");

        javax.swing.GroupLayout panelValorLayout = new javax.swing.GroupLayout(panelValor);
        panelValor.setLayout(panelValorLayout);
        panelValorLayout.setHorizontalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelValorLayout.setVerticalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelValorLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackLayout.createSequentialGroup()
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBackLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(panelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(panelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbreCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbreCaixaActionPerformed
       if(caixa.getStatus().equals("FECHADO")){
          Double valorInicial= caixa.getValoratual();
          caixa= new Caixa();
           caixa.setStatus("ABERTO");
           caixa.setValorinicial(valorInicial);
           caixa.setValoratual(valorInicial);
           try {
               caixabd.adicionarClasseCaixa(caixa);
                jLabelStatus.setText("Caixa Aberto - Aguardando Lançamentos");
                JOptionPane.showMessageDialog(this,"CAIXA ABERTO COM SUCESSO!");
                jButtonAbreCaixa.setEnabled(false);
                jButtonExcluirLancamento.setEnabled(true);
            jButtonFazerLancamento.setEnabled(true);
            jButtonFecharCaixa.setEnabled(true);
            edtTotal.setText("R$ "+valorInicial);
           } catch (Exception ex) {
               Logger.getLogger(FormCaixaDiario.class.getName()).log(Level.SEVERE, null, ex);
               JOptionPane.showMessageDialog(this,"ERRO AO ABRIR CAIXA"+ ex);
           }
           
       }
       
    }//GEN-LAST:event_jButtonAbreCaixaActionPerformed

    private void jButtonFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharCaixaActionPerformed
     if(total!=0){
         FormRealizaFechamentoCaixa form = new FormRealizaFechamentoCaixa(total,caixa);
             form.setVisible(true);  
     }else{
       FormRealizaFechamentoCaixa form = new FormRealizaFechamentoCaixa(caixa.getValorinicial(),caixa);
             form.setVisible(true);    
     }
      
                     
       this.dispose();
       
    }//GEN-LAST:event_jButtonFecharCaixaActionPerformed

    private void jButtonFazerLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFazerLancamentoActionPerformed
     FormLancamentoCaixa form = new FormLancamentoCaixa(this);
     form.setVisible(true);
      
       
    }//GEN-LAST:event_jButtonFazerLancamentoActionPerformed

    private void jButtonExcluirLancamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirLancamentoActionPerformed
         int linhaSelecionada = -1;
       linhaSelecionada = jTableCaixa.getSelectedRow();
       if (linhaSelecionada >= 0) {
//           int idCaixa = (int) jTableCaixa.getValueAt(linhaSelecionada, 3);
          int idCaixaA = (int) model.getValor(linhaSelecionada, 4);
          int op=JOptionPane.showConfirmDialog(this, "Confirma exclusão?","Alerta",JOptionPane.YES_NO_OPTION);
          if(op==JOptionPane.YES_OPTION){
           bd.removerClasseCaixa(idCaixaA);
           model.removeCaixa(linhaSelecionada);
           jTableCaixa.setModel(model);
           JOptionPane.showMessageDialog(this,"Lançamento Excluido");
             try {
                 lista=bd.getListaClasseCaixa();
                 model= new TabelaCaixaDiario(lista);
            jTableCaixa.setModel(model);
            total=bd.getCaixaDiarioSoma();
            total=total+caixa.getValorinicial();
            edtTotal.setText("R$ "+total.toString());
             } catch (Exception ex) {
                 Logger.getLogger(FormCaixaDiario.class.getName()).log(Level.SEVERE, null, ex);
             }
          }
            
       } 
      else {
           JOptionPane.showMessageDialog(null, "É necesário selecionar uma linha.");
       }
    }//GEN-LAST:event_jButtonExcluirLancamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCaixaDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCaixaDiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtTotal;
    private javax.swing.JTextField edtValorInicial;
    private javax.swing.JButton jButtonAbreCaixa;
    private javax.swing.JButton jButtonExcluirLancamento;
    private javax.swing.JButton jButtonFazerLancamento;
    private javax.swing.JButton jButtonFecharCaixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCaixa;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelButton1;
    private javax.swing.JPanel panelButton2;
    private javax.swing.JPanel panelValor;
    // End of variables declaration//GEN-END:variables

    public void retornaLancamento(LancamentoCaixa lancamento) {
       CaixaDiarioBD bd = new CaixaDiarioBD();
        try {
           
            lista=bd.getListaClasseCaixa();
            model= new TabelaCaixaDiario(lista);
            jTableCaixa.setModel(model);
            total=bd.getCaixaDiarioSoma();
            total=total+caixa.getValorinicial();
            edtTotal.setText("R$ "+total.toString());
            
            
        } catch (Exception ex) {
            Logger.getLogger(FormCaixaDiario.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(this,"Erro ao atualizar Caixa "+ ex);
        }
    }
}
