/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fronteira;

import Conection.ClienteBD;
import Conection.ConfiguracaoBD;
import Conection.ItensVendaBD;
import Conection.LancamentoCaixaBD;
import Conection.ProdutoBD;
import Conection.VendaBD;
import Objetos.Cliente;
import Objetos.Configuracao;
import Objetos.ItensVenda;
import Objetos.Produto;
import Objetos.Venda;
import ferramentas.TabelaVendas;
import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class FormGerenciaVendas extends javax.swing.JFrame {

    TabelaVendas model ;
    List<Venda> listaVenda;
    VendaBD bd = new VendaBD();
    Configuracao configuracao = null;
   
    public FormGerenciaVendas() {
        initComponents();
        preencheTabela();
        tornarInvisivel();
        try {
            configuracao = ConfiguracaoBD.getInstancia();
        } catch (Exception ex) {
            Logger.getLogger(FormGerenciaVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
   
     private void preencheTabela(){
         try {
        listaVenda=bd.getListaVenda();
        model = new TabelaVendas(listaVenda);
        tableVenda.setModel(model);
        
        
        tableVenda.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                //A coluna do status é 3
                Object ref = table.getValueAt(row, 5);//Coluna Status
                //Coloca cor em todas as linhas,COLUNA(5) que tem o valor "Cancelada"
                if (ref != null && ref.equals("Cancelada")) {//Se Status for igual a "Cancelada"
                    /* setBackground(Color.RED);//Preenche a linha de vermelho
                    setForeground(Color.WHITE);//E a fonte de branco*/
                    setBackground(new Color(Integer.valueOf(configuracao.getCorFundoCancelado())));
                    setForeground(new Color(Integer.valueOf(configuracao.getCorLetrasCancelado())));
                }else if(ref != null && ref.equals("Condicional")){
                   setBackground(new Color(Integer.valueOf(configuracao.getCorFundoCondicional())));
                    setForeground(new Color(Integer.valueOf(configuracao.getCorLetrasCondicional())));
                }
                    else {
                    boolean sel = isSelected;
                    if (sel == true) {
                            setBackground(getBackground());
                            setForeground(getForeground());
                    } else {//Se Status não for "Cencaleda" 
                            setBackground(Color.WHITE);//Preenche a linha de branco
                            setForeground(new Color(51, 51, 51));//E a fonte de preto
                    }
                }
                if(isSelected){
		                  setBackground(Color.blue);
		setForeground(getForeground()); 
	}
                
                return this;
            }
        });
        
        
        
        
        
    } catch (Exception ex) {
        Logger.getLogger(FormGerenciaVendas.class.getName()).log(Level.SEVERE, null, ex);
    }
     }
     private void tornarInvisivel(){
         
           
                edtPesquisa.setVisible(false);
                SelecionaData.setVisible(false);
                btnPesquisar.setVisible(false);
            
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        frameDadosCliente = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        edtTel = new javax.swing.JTextField();
        edtEndereco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edtBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edtnumero = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtCpf = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVenda = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbCliente = new javax.swing.JRadioButton();
        rbnNVenda = new javax.swing.JRadioButton();
        rbFuncionario = new javax.swing.JRadioButton();
        rbData = new javax.swing.JRadioButton();
        edtPesquisa = new javax.swing.JTextField();
        SelecionaData = new com.toedter.calendar.JDateChooser();
        btnPesquisar = new javax.swing.JButton();

        frameDadosCliente.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        frameDadosCliente.setTitle("Dados Cliente");
        frameDadosCliente.setBackground(new java.awt.Color(255, 255, 255));
        frameDadosCliente.setMinimumSize(new java.awt.Dimension(400, 200));
        frameDadosCliente.setResizable(false);

        jLabel2.setText("Nome:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Endereço:");

        edtNome.setEnabled(false);

        edtTel.setEnabled(false);
        edtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtTelActionPerformed(evt);
            }
        });

        edtEndereco.setEnabled(false);

        jLabel5.setText("Bairro:");

        edtBairro.setEnabled(false);

        jLabel6.setText("Nº");

        edtnumero.setEnabled(false);

        jLabel7.setText("Cpf/Cnpj:");

        edtCpf.setEnabled(false);

        javax.swing.GroupLayout frameDadosClienteLayout = new javax.swing.GroupLayout(frameDadosCliente.getContentPane());
        frameDadosCliente.getContentPane().setLayout(frameDadosClienteLayout);
        frameDadosClienteLayout.setHorizontalGroup(
            frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtEndereco))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameDadosClienteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(22, 22, 22)
                        .addComponent(edtNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameDadosClienteLayout.createSequentialGroup()
                        .addGroup(frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameDadosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(21, 21, 21))
                            .addGroup(frameDadosClienteLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7)))
                        .addGroup(frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(frameDadosClienteLayout.createSequentialGroup()
                                .addComponent(edtBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtnumero))
                            .addGroup(frameDadosClienteLayout.createSequentialGroup()
                                .addComponent(edtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        frameDadosClienteLayout.setVerticalGroup(
            frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frameDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(edtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Vendas");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableVenda);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar Venda");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adicionar.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Editar.gif"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busca.png"))); // NOI18N
        jButton1.setText("Visualizar Dados Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar por:"));

        buttonGroup1.add(rbCliente);
        rbCliente.setText("Cliente");
        rbCliente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbClienteStateChanged(evt);
            }
        });

        buttonGroup1.add(rbnNVenda);
        rbnNVenda.setText("Nº Venda");
        rbnNVenda.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbnNVendaStateChanged(evt);
            }
        });

        buttonGroup1.add(rbFuncionario);
        rbFuncionario.setText("Funcionario");
        rbFuncionario.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbFuncionarioStateChanged(evt);
            }
        });

        buttonGroup1.add(rbData);
        rbData.setText("Data Entrada");
        rbData.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbDataStateChanged(evt);
            }
        });
        rbData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDataActionPerformed(evt);
            }
        });

        edtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtPesquisaKeyPressed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busca.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbnNVenda)
                    .addComponent(rbCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbFuncionario)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar)
                    .addComponent(SelecionaData, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbnNVenda)
                            .addComponent(rbFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbCliente)
                            .addComponent(rbData)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelecionaData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)))
                .addGap(2, 2, 2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnCancelar)
                    .addComponent(btnAlterar)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCancelar, btnIncluir, jButton1});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       preencheTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void tableVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVendaMouseClicked
        if (evt.getClickCount() > 1) {  
 seleciona();
}  
        
    }//GEN-LAST:event_tableVendaMouseClicked

    private void devolveEstoque(Venda venda){
        ProdutoBD produtoBd = new ProdutoBD();
        ItensVendaBD itensBd = new ItensVendaBD();
        Double qtdEstoqueProduto= 0.0;
        try {//devolver estoque Produtos
                    
                    List<ItensVenda> listaDevolverEstoque = itensBd.getListaItensVendaByIdVenda(venda.getId());
                    
                    
                    Iterator<ItensVenda> iterator = listaDevolverEstoque.iterator();
                    while(iterator.hasNext()){
                         ItensVenda itensVenda = iterator.next();
                         int qtd = itensVenda.getQtd();
                         Produto produto = produtoBd.getProdutoById(itensVenda.getId_produto());
                     qtdEstoqueProduto = produto.getQtd_estoque();
                qtdEstoqueProduto += qtd;
                produto.setQtd_estoque(qtdEstoqueProduto);
                    produtoBd.AtualizaProduto(produto);
                    }
                   
                } catch (Exception ex) {
                    Logger.getLogger(FormFinalizaVenda.class.getName()).log(Level.SEVERE, null, ex);
                      JOptionPane.showMessageDialog(this, "Erro ao devolver estoques produtos venda " + ex);
                }
                // devolver estoque produtos
                
                
                itensBd.removerItemByIdVenda(venda.getId());//remover itens da venda;
    }
    
    
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
 int linhaSelecionada = -1;
        Venda venda = null;
        linhaSelecionada = tableVenda.getSelectedRow();
        if (linhaSelecionada >= 0) {
          int idVenda = (int) tableVenda.getValueAt(linhaSelecionada, 0);

            venda = bd.getVendaById(idVenda);
            venda.setSituacao(2);
            int resposta= JOptionPane.showConfirmDialog(this, "Confirma Cancelamento de Venda?","Atenção",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
          if(resposta==JOptionPane.YES_OPTION){  
     try {
         new VendaBD().AtualizaVenda(venda);
         new LancamentoCaixaBD().removerlancamentoCaixaByIdVenda(venda.getId());
         devolveEstoque(venda);
          JOptionPane.showMessageDialog(null, "Venda cancelada com sucesso");
          preencheTabela();
     } catch (Exception ex) {
         Logger.getLogger(FormGerenciaVendas.class.getName()).log(Level.SEVERE, null, ex);
         JOptionPane.showMessageDialog(null, "Erro ao cancelar Venda.");
     }
          
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Venda");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed
    }
    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        FormVendaCompleta form = new FormVendaCompleta();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnIncluirActionPerformed
public void seleciona() {
        int linhaSelecionada = -1;
        Venda venda = null;
        linhaSelecionada = tableVenda.getSelectedRow();
        if (linhaSelecionada >= 0) {
          int idVenda = (int) tableVenda.getValueAt(linhaSelecionada, 0);

            venda = bd.getVendaById(idVenda);
            
            FormVendaCompleta formVendaCompleda = new FormVendaCompleta(venda);
            formVendaCompleda.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma Venda");
        }

    }
    
    
    
    
    private void rbClienteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbClienteStateChanged
        if(rbCliente.isSelected()){
            if(edtPesquisa.isVisible()==true){
                SelecionaData.setVisible(false);
                btnPesquisar.setVisible(false);
            }else{
                edtPesquisa.setVisible(true);
                btnPesquisar.setVisible(false);
                SelecionaData.setVisible(false);
            }
        }
        validate();        // TODO add your handling code here:
    }//GEN-LAST:event_rbClienteStateChanged

    private void rbnNVendaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbnNVendaStateChanged
        // TODO add your handling code here:
        if(rbnNVenda.isSelected()){
            if(edtPesquisa.isVisible()==true){
                btnPesquisar.setVisible(false);
                SelecionaData.setVisible(false);
            }else{
                edtPesquisa.setVisible(true);
                SelecionaData.setVisible(false);
                btnPesquisar.setVisible(false);
            }
        }
        validate();

    }//GEN-LAST:event_rbnNVendaStateChanged

    private void rbFuncionarioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbFuncionarioStateChanged
        if(rbFuncionario.isSelected()){
            if(edtPesquisa.isVisible()==true){
                SelecionaData.setVisible(false);
                btnPesquisar.setVisible(false);
            }else{
                edtPesquisa.setVisible(true);
                SelecionaData.setVisible(false);
                btnPesquisar.setVisible(false);
            }
        }
        validate();        // TODO add your handling code here:
    }//GEN-LAST:event_rbFuncionarioStateChanged

    private void rbDataStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbDataStateChanged
        if(rbData.isSelected()){
            if(edtPesquisa.isVisible()==true){
                SelecionaData.setVisible(true);
                btnPesquisar.setVisible(true);
                edtPesquisa.setVisible(false);
            }else{
                edtPesquisa.setVisible(false);
                btnPesquisar.setVisible(true);
                SelecionaData.setVisible(true);
            }
        }
        validate();        // TODO add your handling code here:
    }//GEN-LAST:event_rbDataStateChanged

    private void edtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtPesquisaKeyPressed
        TabelaVendas tabela_model = (TabelaVendas) tableVenda.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
        tableVenda.setRowSorter(sorter);
        String text ="(?i)"+edtPesquisa.getText().toUpperCase();
        if (text.length() == 0)
        {
            sorter.setRowFilter(null);
        }
        else
        {
            try
            {
                if(rbCliente.isSelected()){
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text, 1));
                }else if(rbFuncionario.isSelected()){
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text,2));

                }else if(rbnNVenda.isSelected()){
                    sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text,0));

                }
            }
            catch (PatternSyntaxException pse)
            {
                System.err.println("Erro");
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_edtPesquisaKeyPressed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        TabelaVendas tabela_model = (TabelaVendas) tableVenda.getModel();
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tabela_model);
        tableVenda.setRowSorter(sorter);

        DateFormat f = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String text ="(?i)"+f.format(SelecionaData.getDate());
        if (text.length() == 0)
        {
            sorter.setRowFilter(null);
        }
        else
        {
            try
            {

                sorter.setRowFilter(RowFilter.regexFilter("(?i)"+text, 4));

            }
            catch (PatternSyntaxException pse)
            {
                System.err.println("Erro");
            }
        }

        System.out.println();        // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void rbDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDataActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       seleciona();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int linhaSelecionada = -1;
        Venda venda = null;
        linhaSelecionada = tableVenda.getSelectedRow();
        if (linhaSelecionada >= 0) {
          int idVenda = (int) tableVenda.getValueAt(linhaSelecionada, 0);

            venda = bd.getVendaById(idVenda);
            Cliente cliente = new ClienteBD().getClienteById(venda.getId_Cliente());
            edtNome.setText(cliente.getNome());
                   edtEndereco.setText(cliente.getEndereco());
                   edtBairro.setText(cliente.getBairro());
                   edtnumero.setText(String.valueOf(cliente.getNumero()));
                   edtCpf.setText(cliente.getCpf());
                   edtTel.setText(cliente.getTelefone());
                   frameDadosCliente.setLocationRelativeTo(null);
                   frameDadosCliente.setVisible(true);
                   
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma venda");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void edtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGerenciaVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGerenciaVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser SelecionaData;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edtBairro;
    private javax.swing.JTextField edtCpf;
    private javax.swing.JTextField edtEndereco;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtPesquisa;
    private javax.swing.JTextField edtTel;
    private javax.swing.JTextField edtnumero;
    private javax.swing.JFrame frameDadosCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCliente;
    private javax.swing.JRadioButton rbData;
    private javax.swing.JRadioButton rbFuncionario;
    private javax.swing.JRadioButton rbnNVenda;
    private javax.swing.JTable tableVenda;
    // End of variables declaration//GEN-END:variables
}
