package Objetos;
// Generated 25/07/2016 15:45:24 by Hibernate Tools 4.3.1



/**
 * Unidadecomercial generated by hbm2java
 */
public class Unidadecomercial  implements java.io.Serializable {

    


     private Integer idUnidadeComercial;
     private String sigla;
     private Double valor;

    public Unidadecomercial() {
    }
@Override
    public String toString() {
        return sigla;
    }
    public Unidadecomercial(String sigla, Double valor) {
       this.sigla = sigla;
       this.valor = valor;
    }
   
    public Integer getIdUnidadeComercial() {
        return this.idUnidadeComercial;
    }
    
    public void setIdUnidadeComercial(Integer idUnidadeComercial) {
        this.idUnidadeComercial = idUnidadeComercial;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }




}


